# Generated by Django 5.2 on 2025-09-17 05:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_credito', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('linea', models.CharField(choices=[('EMPRENDIMIENTO', 'Emprendimiento'), ('LIBRANZA', 'Libranza')], max_length=20)),
                ('estado', models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('FIRMADO', 'Firmado'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado')], default='SOLICITUD', max_length=20)),
                ('documento_enviado', models.BooleanField(default=False, help_text='Indica si el pagaré ha sido enviado para firma.')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='CreditoEmprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('numero_cedula', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField()),
                ('celular_wh', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('estado_civil', models.CharField(max_length=20)),
                ('numero_personas_cargo', models.IntegerField()),
                ('nombre_negocio', models.CharField(max_length=100)),
                ('ubicacion_negocio', models.TextField()),
                ('tiempo_operando', models.CharField(max_length=50)),
                ('dias_trabajados_sem', models.IntegerField()),
                ('prod_serv_ofrec', models.TextField()),
                ('ingresos_prom_mes', models.CharField(max_length=50)),
                ('cli_aten_day', models.IntegerField()),
                ('inventario', models.CharField(max_length=2)),
                ('nomb_ref_per1', models.CharField(max_length=100)),
                ('cel_ref_per1', models.CharField(max_length=20)),
                ('rel_ref_per1', models.CharField(max_length=50)),
                ('nomb_ref_cl1', models.CharField(max_length=100)),
                ('cel_ref_cl1', models.CharField(max_length=20)),
                ('rel_ref_cl1', models.CharField(max_length=50)),
                ('ref_conoc_lid_com', models.CharField(max_length=2)),
                ('foto_negocio', models.FileField(help_text='Solo se permiten archivos PDF', upload_to='fotos_negocios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('desc_fotos_neg', models.TextField()),
                ('tipo_cta_mno', models.CharField(max_length=20)),
                ('ahorro_tand_alc', models.CharField(max_length=2)),
                ('depend_h', models.CharField(max_length=2)),
                ('desc_cred_nec', models.TextField()),
                ('redes_soc', models.CharField(max_length=2)),
                ('fotos_prod', models.CharField(max_length=2)),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo_pendiente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_proximo_pago', models.DateField(blank=True, null=True)),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('credito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_emprendimiento', to='gestion_creditos.credito')),
            ],
        ),
        migrations.CreateModel(
            name='CreditoLibranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_credito', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(100000)])),
                ('plazo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('cedula_frontal', models.FileField(upload_to='credito_libranza/cedulas/')),
                ('cedula_trasera', models.FileField(upload_to='credito_libranza/cedulas/')),
                ('certificado_laboral', models.FileField(upload_to='credito_libranza/certificados_laborales/')),
                ('desprendible_nomina', models.FileField(upload_to='credito_libranza/desprendibles_nomina/')),
                ('certificado_bancario', models.FileField(upload_to='credito_libranza/certificados_bancarios/')),
                ('credito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_libranza', to='gestion_creditos.credito')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_creditos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_pago', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='gestion_creditos.credito')),
            ],
        ),
    ]
