# Generated by Django 5.2 on 2025-09-20 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoemprendimiento',
            name='tasa_interes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tasa de interés mensual', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='fecha_proximo_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='monto_aprobado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='saldo_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='tasa_interes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tasa de interés mensual', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='valor_cuota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado')], default='SOLICITUD', max_length=30),
        ),
        migrations.AlterField(
            model_name='credito',
            name='linea',
            field=models.CharField(choices=[('EMPRENDIMIENTO', 'Emprendimiento'), ('LIBRANZA', 'Libranza')], max_length=30),
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('SOLICITUD', 'Solicitud'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado')], max_length=30, null=True)),
                ('estado_nuevo', models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, help_text='Razón o motivo del cambio de estado.', null=True)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes_pago/')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='gestion_creditos.credito')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-fecha'],
            },
        ),
    ]
