# Generated by Django 5.2 on 2025-09-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0002_creditoemprendimiento_tasa_interes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_FIRMA', 'Pendiente Firma'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado')], default='SOLICITUD', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('SOLICITUD', 'Solicitud'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_FIRMA', 'Pendiente Firma'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_FIRMA', 'Pendiente Firma'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado')], max_length=30),
        ),
    ]
