# Generated by Django 5.2 on 2025-10-08 02:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0003_alter_credito_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTasaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_anual_efectiva', models.DecimalField(decimal_places=2, default=5.0, help_text='Tasa anual efectiva (EA) en porcentaje', max_digits=5)),
                ('fecha_vigencia', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Tasa',
                'verbose_name_plural': 'Configuraciones de Tasas',
                'ordering': ['-fecha_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='CuentaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('INVERSIONISTA', 'Inversionista'), ('EMPRENDEDOR', 'Cliente Emprendimiento'), ('EMPLEADO', 'Cliente Libranza'), ('NATURAL', 'Persona Natural')], max_length=20)),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_objetivo', models.DecimalField(decimal_places=2, default=1000000, help_text='Meta de ahorro del usuario', max_digits=12)),
                ('emprendimientos_financiados', models.IntegerField(default=0)),
                ('familias_beneficiadas', models.IntegerField(default=0)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_ahorro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta de Ahorro',
                'verbose_name_plural': 'Cuentas de Ahorro',
            },
        ),
        migrations.CreateModel(
            name='MovimientoAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPOSITO_ONLINE', 'Depósito Online'), ('DEPOSITO_OFFLINE', 'Consignación Offline'), ('RETIRO', 'Retiro'), ('INTERES', 'Interés Generado'), ('AJUSTE_ADMIN', 'Ajuste Administrativo')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PROCESADO', 'Procesado')], default='PENDIENTE', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='billetera/comprobantes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('nota_admin', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion_creditos.cuentaahorro')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_procesados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Ahorro',
                'verbose_name_plural': 'Movimientos de Ahorro',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
