# Generated by Django 5.2 on 2025-10-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0004_configuraciontasainteres_cuentaahorro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoemprendimiento',
            name='capital_original_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='creditoemprendimiento',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='creditoemprendimiento',
            name='iva_comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='creditoemprendimiento',
            name='total_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='capital_original_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='iva_comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='total_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='creditoemprendimiento',
            name='saldo_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='creditolibranza',
            name='saldo_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
