# Generated by Django 5.2 on 2026-06-30 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0033_add_special_libranza_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='requiere_aprobadores_distintos_libranza',
            field=models.BooleanField(default=True, verbose_name='Requiere aprobadores distintos en libranza'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='requiere_doble_aprobacion_libranza',
            field=models.BooleanField(default=False, verbose_name='Requiere doble aprobacion libranza'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('PENDIENTE_APROBACION_FINAL', 'Pendiente aprobacion final'), ('EN_REVISION', 'En Revisión'), ('APROBADO_PAGADOR', 'Aprobado por Pagador'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_FIRMA', 'Pendiente Firma'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado')], default='SOLICITUD', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('SOLICITUD', 'Solicitud'), ('PENDIENTE_APROBACION_FINAL', 'Pendiente aprobacion final'), ('EN_REVISION', 'En Revisión'), ('APROBADO_PAGADOR', 'Aprobado por Pagador'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_FIRMA', 'Pendiente Firma'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('PENDIENTE_APROBACION_FINAL', 'Pendiente aprobacion final'), ('EN_REVISION', 'En Revisión'), ('APROBADO_PAGADOR', 'Aprobado por Pagador'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_FIRMA', 'Pendiente Firma'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado')], max_length=30),
        ),
        migrations.CreateModel(
            name='AprobacionPagadorLibranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('NIVEL_1', 'Nivel 1'), ('FINAL', 'Final')], max_length=20)),
                ('decision', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_pagador_libranza', to='gestion_creditos.credito')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_pagador_libranza', to='gestion_creditos.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones_pagador_libranza', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aprobacion pagador libranza',
                'verbose_name_plural': 'Aprobaciones pagador libranza',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['credito', 'nivel', 'decision'], name='apr_pag_lib_cred_niv_dec_idx'), models.Index(fields=['empresa', '-created_at'], name='apr_pag_lib_emp_fecha_idx')],
            },
        ),
    ]
