# Generated by Django 5.2 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0034_empresa_requiere_aprobadores_distintos_libranza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestructuracioncredito',
            name='tipo_abono',
            field=models.CharField(
                choices=[
                    ('NORMAL', 'Abono Normal'),
                    ('CAPITAL', 'Abono a Capital - reducir cuota'),
                    ('CAPITAL_REDUCIR_PLAZO', 'Abono a Capital - reducir plazo'),
                    ('MAYOR', 'Abono Mayor (>2 cuotas)'),
                ],
                default='NORMAL',
                max_length=32,
            ),
        ),
    ]
