# Generated by Django 5.2 on 2026-07-18 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0034_empresa_requiere_aprobadores_distintos_libranza_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaNumeroCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(unique=True)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Secuencia de numero de credito',
                'verbose_name_plural': 'Secuencias de numeros de credito',
            },
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='cargo_actividad_contractual',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='contrato_prestacion_servicios',
            field=models.FileField(blank=True, null=True, upload_to='credito_libranza/contratos_prestadores/', verbose_name='Contrato de prestacion de servicios'),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='es_prestador_servicios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='escenario_credito',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='fecha_fin_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='fecha_inicio_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='valor_pagado_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='valor_pendiente_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='creditolibranza',
            name='valor_total_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='OrigenCreditoPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_id', models.PositiveBigIntegerField(unique=True)),
                ('gate_version', models.CharField(max_length=64)),
                ('clave_idempotencia', models.CharField(max_length=180, unique=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('ERROR_CONTROLADO', 'Error controlado')], default='EN_PROCESO', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origenes_credito_prestador_creados', to=settings.AUTH_USER_MODEL)),
                ('credito', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origen_prestador', to='gestion_creditos.credito')),
                ('credito_libranza', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origen_prestador', to='gestion_creditos.creditolibranza')),
            ],
            options={
                'verbose_name': 'Origen de credito de prestador',
                'verbose_name_plural': 'Origenes de creditos de prestadores',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['estado', '-created_at'], name='orig_prest_estado_idx')],
            },
        ),
    ]
