# Generated by Django 5.2 on 2026-06-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0035_alter_credito_options_whatsappinternalapiauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='departamento',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_principal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipio',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
