# Generated by Django 5.2 on 2026-08-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0035_alter_reestructuracioncredito_tipo_abono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('PENDIENTE_APROBACION_FINAL', 'Pendiente aprobacion final'), ('EN_REVISION', 'En Revisión'), ('APROBADO_PAGADOR', 'Aprobado por Pagador'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_FIRMA', 'Pendiente Firma'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='SOLICITUD', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('SOLICITUD', 'Solicitud'), ('PENDIENTE_APROBACION_FINAL', 'Pendiente aprobacion final'), ('EN_REVISION', 'En Revisión'), ('APROBADO_PAGADOR', 'Aprobado por Pagador'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_FIRMA', 'Pendiente Firma'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('PENDIENTE_APROBACION_FINAL', 'Pendiente aprobacion final'), ('EN_REVISION', 'En Revisión'), ('APROBADO_PAGADOR', 'Aprobado por Pagador'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_FIRMA', 'Pendiente Firma'), ('FIRMADO', 'Firmado'), ('PENDIENTE_TRANSFERENCIA', 'Pendiente por Transferencia'), ('ACTIVO', 'Activo'), ('EN_MORA', 'En Mora'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], max_length=30),
        ),
    ]
