# Generated by Django 5.2 on 2026-08-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0037_merge_hotfixes_produccion_prestadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestado',
            name='clave_idempotencia',
            field=models.CharField(blank=True, help_text='Clave persistente para operaciones de estado idempotentes.', max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='calculado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='capital_total_financiado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='cuota_aprobada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='fondo_garantia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='monto_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='otros_componentes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='otros_costos_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='plazo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='porcentaje_comision',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='porcentaje_fondo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='porcentaje_iva',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='porcentaje_seguro',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='seguro_vida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='snapshot_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='tasa_mensual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='total_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='total_intereses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='version_configuracion',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='version_formula',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='version_politica',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='origencreditoprestador',
            name='version_score',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
