# Generated by Django 5.2 on 2026-08-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0039_historialestado_clave_idempotencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagare',
            name='version_plantilla',
            field=models.CharField(default='1.0', help_text='Identificador versionado de la plantilla legal usada', max_length=32),
        ),
    ]
