# Generated by Django 5.2 on 2026-08-25 23:56

import django.core.validators
import django.db.models.deletion
import gestion_creditos.models
import gestion_creditos.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0041_empresa_ciudad_empresa_departamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('RUT', 'RUT'), ('CAMARA_COMERCIO', 'Cámara de Comercio'), ('CEDULA_REPRESENTANTE_LEGAL', 'Cédula del representante legal')], max_length=40)),
                ('archivo', models.FileField(storage=gestion_creditos.storage.PrivateDocumentStorage(), upload_to=gestion_creditos.models.ruta_documento_empresa, validators=[django.core.validators.FileExtensionValidator(('pdf', 'jpg', 'jpeg', 'png', 'webp')), gestion_creditos.models.validar_archivo_documento_empresa])),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('REEMPLAZADO', 'Reemplazado'), ('ANULADO', 'Anulado')], default='VIGENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_empresa_cargados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_institucionales', to='gestion_creditos.empresa')),
            ],
            options={
                'verbose_name': 'Documento de empresa',
                'verbose_name_plural': 'Documentos de empresa',
                'ordering': ['empresa', 'tipo_documento', '-creado_en'],
                'indexes': [models.Index(fields=['empresa', 'tipo_documento', 'estado'], name='doc_empresa_tipo_estado_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('empresa', 'tipo_documento'), name='uniq_doc_empresa_tipo_activo')],
            },
        ),
    ]
