# Generated by Django 5.2 on 2026-08-26 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0042_documentoempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionOriginacionLibranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_referencia', models.DateTimeField()),
                ('codigo_politica', models.CharField(max_length=64)),
                ('version_politica', models.CharField(max_length=40)),
                ('origen', models.CharField(choices=[('NORMAL', 'Normal'), ('ESPECIAL', 'Especial')], max_length=10)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('plazo', models.PositiveSmallIntegerField()),
                ('porcentaje_originacion', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('valor_originacion', models.DecimalField(decimal_places=2, max_digits=14)),
                ('porcentaje_iva', models.DecimalField(decimal_places=4, max_digits=7)),
                ('valor_iva', models.DecimalField(decimal_places=2, max_digits=14)),
                ('calculado_en', models.DateTimeField(auto_now_add=True)),
                ('snapshot_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('credito', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='condicion_originacion_libranza', to='gestion_creditos.credito')),
                ('regla_especial', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='condicion_originacion', to='gestion_creditos.creditoreglaespecialaudit')),
            ],
            options={
                'verbose_name': 'Condicion de originacion Libranza',
                'verbose_name_plural': 'Condiciones de originacion Libranza',
                'ordering': ['-calculado_en'],
                'indexes': [models.Index(fields=['codigo_politica', 'fecha_referencia'], name='cond_orig_lib_pol_fecha_idx')],
            },
        ),
    ]
