# Generated by Django 5.2 on 2026-08-29 22:05

import django.core.validators
import django.db.models.deletion
import gestion_creditos.models
import gestion_creditos.storage
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0043_condicionoriginacionlibranza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialpago',
            name='metodo_pago',
            field=models.CharField(choices=[('NO_DEFINIDO', 'No definido'), ('WOMPI', 'Wompi'), ('TRANSFERENCIA_DIRECTA', 'Transferencia directa'), ('OFFLINE_MANUAL', 'Offline manual'), ('BREB', 'BRE-B')], default='NO_DEFINIDO', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialpago',
            name='origen_registro',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('PASARELA_WOMPI', 'Pasarela Wompi'), ('CARGA_MASIVA_EMPRESA', 'Carga masiva empresa'), ('REGISTRO_MANUAL_ADMIN', 'Registro manual admin'), ('REGISTRO_MANUAL_PAGADOR', 'Registro manual pagador'), ('REPORTE_BREB', 'Reporte BRE-B verificado')], default='LEGACY', max_length=32),
        ),
        migrations.CreateModel(
            name='ConfiguracionPagoBREB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('nombre_receptor', models.CharField(max_length=160)),
                ('entidad_financiera', models.CharField(max_length=120)),
                ('tipo_llave', models.CharField(choices=[('CELULAR', 'Celular'), ('CEDULA_NIT', 'Cédula o NIT'), ('CORREO', 'Correo'), ('ALFANUMERICA', 'Llave alfanumérica')], max_length=20)),
                ('llave_mostrable', models.CharField(max_length=160)),
                ('qr', models.ImageField(storage=gestion_creditos.storage.PrivateDocumentStorage(), upload_to=gestion_creditos.models.ruta_archivo_breb, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png')), gestion_creditos.models.validar_archivo_documento_empresa])),
                ('instrucciones', models.TextField(blank=True)),
                ('hash_qr', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_breb_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de pago BRE-B',
                'verbose_name_plural': 'Configuraciones de pago BRE-B',
                'ordering': ['-activo', '-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='PagoBREB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_reportado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_pago_reportada', models.DateField()),
                ('referencia_reportada', models.CharField(blank=True, max_length=120)),
                ('comprobante', models.FileField(storage=gestion_creditos.storage.PrivateDocumentStorage(), upload_to=gestion_creditos.models.ruta_archivo_breb, validators=[django.core.validators.FileExtensionValidator(('pdf', 'jpg', 'jpeg', 'png')), gestion_creditos.models.validar_archivo_documento_empresa])),
                ('estado', models.CharField(choices=[('PENDIENTE_VERIFICACION', 'Pendiente de verificación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='PENDIENTE_VERIFICACION', max_length=30)),
                ('hash_comprobante', models.CharField(db_index=True, editable=False, max_length=64)),
                ('clave_idempotencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_reportados', to='gestion_creditos.configuracionpagobreb')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_breb', to='gestion_creditos.credito')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_breb', to='gestion_creditos.empresa')),
                ('historial_pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_breb', to='gestion_creditos.historialpago')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_breb_revisados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_breb_reportados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago BRE-B reportado',
                'verbose_name_plural': 'Pagos BRE-B reportados',
                'ordering': ['-creado_en'],
                'permissions': [('review_pagobreb', 'Puede verificar y decidir pagos BRE-B')],
            },
        ),
        migrations.AddConstraint(
            model_name='configuracionpagobreb',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('activo',), name='uniq_config_pago_breb_activa'),
        ),
        migrations.AddIndex(
            model_name='pagobreb',
            index=models.Index(fields=['estado', '-creado_en'], name='pago_breb_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='pagobreb',
            index=models.Index(fields=['credito', '-creado_en'], name='pago_breb_credito_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagobreb',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'APROBADO'), _negated=True), models.Q(('historial_pago__isnull', False), ('valor_aprobado__isnull', False)), _connector='OR'), name='pago_breb_aprobado_con_aplicacion'),
        ),
    ]
