# Generated by Django 5.2 on 2026-09-03 03:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrar_pagos_individuales_a_detalle(apps, schema_editor):
    PagoBREB = apps.get_model('gestion_creditos', 'PagoBREB')
    PagoBREBDetalle = apps.get_model('gestion_creditos', 'PagoBREBDetalle')
    for pago in PagoBREB.objects.exclude(credito_id=None).iterator():
        PagoBREBDetalle.objects.get_or_create(
            pago_breb_id=pago.pk,
            credito_id=pago.credito_id,
            cuota_id=None,
            defaults={
                'valor_reportado': pago.valor_reportado,
                'valor_aprobado': pago.valor_aprobado,
                'historial_pago_id': pago.historial_pago_id,
                'aplicado_en': pago.revisado_en if pago.historial_pago_id else None,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0044_configuracion_pago_breb_y_pagobreb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoBREBDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_vencimiento_snapshot', models.DateField(blank=True, null=True)),
                ('valor_cuota_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_reportado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detalle de pago BRE-B',
                'verbose_name_plural': 'Detalles de pagos BRE-B',
                'ordering': ['pago_breb_id', 'credito_id', 'numero_cuota_snapshot', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='pagobreb',
            name='pago_breb_aprobado_con_aplicacion',
        ),
        migrations.AddField(
            model_name='pagobreb',
            name='fingerprint_reporte',
            field=models.CharField(blank=True, editable=False, help_text='Huella idempotente del reporte agrupado y sus obligaciones.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pagobreb',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagobreb',
            name='credito',
            field=models.ForeignKey(blank=True, help_text='Credito individual legado. Los reportes agrupados usan sus detalles.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_breb', to='gestion_creditos.credito'),
        ),
        migrations.AddConstraint(
            model_name='pagobreb',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'APROBADO'), _negated=True), ('valor_aprobado__isnull', False), _connector='OR'), name='pago_breb_aprobado_con_aplicacion'),
        ),
        migrations.AddField(
            model_name='pagobrebdetalle',
            name='credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pago_breb', to='gestion_creditos.credito'),
        ),
        migrations.AddField(
            model_name='pagobrebdetalle',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pago_breb', to='gestion_creditos.cuotaamortizacion'),
        ),
        migrations.AddField(
            model_name='pagobrebdetalle',
            name='historial_pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_breb', to='gestion_creditos.historialpago'),
        ),
        migrations.AddField(
            model_name='pagobrebdetalle',
            name='pago_breb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion_creditos.pagobreb'),
        ),
        migrations.RunPython(
            migrar_pagos_individuales_a_detalle,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='pagobrebdetalle',
            constraint=models.UniqueConstraint(condition=models.Q(('cuota__isnull', False)), fields=('pago_breb', 'cuota'), name='uniq_pago_breb_obligacion_cuota'),
        ),
        migrations.AddConstraint(
            model_name='pagobrebdetalle',
            constraint=models.CheckConstraint(condition=models.Q(('valor_reportado__gt', Decimal('0.00'))), name='pago_breb_detalle_reportado_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pagobrebdetalle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aplicado_en__isnull', True), ('historial_pago__isnull', True), ('valor_aprobado__isnull', True)), models.Q(('aplicado_en__isnull', False), ('historial_pago__isnull', False), ('valor_aprobado__isnull', False)), _connector='OR'), name='pago_breb_detalle_aplicacion_completa'),
        ),
    ]
