# Generated by Django 5.2 on 2026-09-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0045_pago_breb_agrupado_pagadores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialpago',
            options={'ordering': ['-fecha_aplicacion', '-fecha_pago'], 'permissions': [('reconcile_manual_payment_rounding', 'Puede reconciliar redondeos de pagos manuales')], 'verbose_name': 'Historial de Pago', 'verbose_name_plural': 'Historial de Pagos'},
        ),
    ]
