# Generated by Django 5.2 on 2026-09-12 19:33

import django.db.models.deletion
import gestion_creditos.models
import gestion_creditos.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0019_captura_documental_privada'),
        ('gestion_creditos', '0046_historialpago_reconcile_manual_payment_rounding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditolibranza',
            name='cedula_frontal',
            field=models.FileField(storage=gestion_creditos.storage.DocumentosSolicitudStorage(), upload_to='credito_libranza/cedulas/', verbose_name='Cédula (frontal)'),
        ),
        migrations.AlterField(
            model_name='creditolibranza',
            name='cedula_trasera',
            field=models.FileField(storage=gestion_creditos.storage.DocumentosSolicitudStorage(), upload_to='credito_libranza/cedulas/', verbose_name='Cédula (trasera)'),
        ),
        migrations.CreateModel(
            name='SesionCapturaDocumental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('producto', models.CharField(choices=[('LIBRANZA', 'Libranza'), ('PRESTADORES', 'Prestadores')], max_length=16)),
                ('proposito', models.CharField(default='CEDULA', editable=False, max_length=16)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CANJEADA', 'Canjeada'), ('FINALIZADA', 'Finalizada'), ('UTILIZADA', 'Utilizada'), ('REVOCADA', 'Revocada'), ('EXPIRADA', 'Expirada')], default='ABIERTA', max_length=16)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('vinculo_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('expira_en', models.DateTimeField(db_index=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('canjeado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('utilizado_en', models.DateTimeField(blank=True, null=True)),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_creditos.credito')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contractors.contractorapplication')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_identity_documents', 'Puede consultar documentos privados de identidad')],
            },
        ),
        migrations.CreateModel(
            name='EventoCapturaDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=32)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='gestion_creditos.sesioncapturadocumental')),
            ],
        ),
        migrations.CreateModel(
            name='CapturaDocumentoIdentidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lado', models.CharField(choices=[('FRONTAL', 'Frontal'), ('TRASERA', 'Trasera')], max_length=8)),
                ('archivo', models.FileField(storage=gestion_creditos.storage.PrivateDocumentStorage(), upload_to=gestion_creditos.models.ruta_captura_documental)),
                ('hash_archivo', models.CharField(editable=False, max_length=64)),
                ('estado_tecnico', models.CharField(default='VALIDO_TECNICAMENTE', editable=False, max_length=24)),
                ('identidad', models.CharField(default='IDENTIDAD_NO_VERIFICADA', editable=False, max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('purgado_en', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capturas', to='gestion_creditos.sesioncapturadocumental')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sesioncapturadocumental',
            constraint=models.CheckConstraint(condition=models.Q(('proposito', 'CEDULA')), name='captura_proposito_cedula'),
        ),
        migrations.AddConstraint(
            model_name='sesioncapturadocumental',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('producto', 'LIBRANZA'), ('solicitud__isnull', True)), models.Q(('credito__isnull', True), ('producto', 'PRESTADORES')), _connector='OR'), name='captura_contexto_producto'),
        ),
        migrations.AddConstraint(
            model_name='capturadocumentoidentidad',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('sesion', 'lado'), name='captura_lado_activo_unico'),
        ),
    ]
