# Generated by Django 5.2 on 2026-09-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0047_captura_documental_privada'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncapturadocumental',
            name='capture_grant_expira_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sesioncapturadocumental',
            name='capture_grant_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='sesioncapturadocumental',
            name='capture_grant_revocado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
