# Generated by Django 5.2 on 2026-09-17 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_creditos', '0048_captura_documental_capture_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionPagoBREB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('NUEVO_PENDIENTE', 'Nuevo reporte pendiente')], default='NUEVO_PENDIENTE', max_length=30)),
                ('canal', models.CharField(choices=[('EMAIL_INTERNO', 'Correo interno')], default='EMAIL_INTERNO', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('FALLIDA', 'Fallida sin envio'), ('INCIERTA', 'Resultado incierto, revisar antes de reenviar')], default='PENDIENTE', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_intento_en', models.DateTimeField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('numero_intentos', models.PositiveIntegerField(default=0)),
                ('codigo_error', models.CharField(blank=True, max_length=64)),
                ('pago_breb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='gestion_creditos.pagobreb')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estado', 'creado_en'], name='breb_notif_estado_fecha_idx')],
                'constraints': [models.UniqueConstraint(fields=('pago_breb', 'tipo_evento', 'canal'), name='uniq_breb_evento_canal')],
            },
        ),
    ]
