# Generated by Django 5.2 on 2026-09-22 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0019_captura_documental_privada'),
        ('gestion_creditos', '0049_notificacion_pago_breb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesamientoOCRDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('REQUIERE_REVISION', 'Requiere revision'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('motor', models.CharField(default='tesseract', max_length=32)),
                ('version_motor', models.CharField(blank=True, max_length=80)),
                ('version_parser', models.CharField(max_length=32)),
                ('configuracion', models.JSONField(default=dict)),
                ('firma_configuracion', models.CharField(max_length=64)),
                ('firma_inputs', models.CharField(max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('numero_intentos', models.PositiveIntegerField(default=0)),
                ('reservado_hasta', models.DateTimeField(blank=True, null=True)),
                ('token_ejecucion', models.UUIDField(blank=True, editable=False, null=True)),
                ('codigo_error', models.CharField(blank=True, max_length=64)),
                ('vigente', models.BooleanField(default=True)),
                ('purgado_en', models.DateTimeField(blank=True, null=True)),
                ('tipo_documento_detectado', models.CharField(default='DESCONOCIDO', max_length=20)),
                ('lado_frontal_detectado', models.CharField(default='DESCONOCIDO', max_length=12)),
                ('lado_trasera_detectado', models.CharField(default='DESCONOCIDO', max_length=12)),
                ('numero_documento_bruto', models.CharField(blank=True, max_length=80)),
                ('numero_documento_normalizado', models.CharField(blank=True, max_length=20)),
                ('nombres_bruto', models.CharField(blank=True, max_length=240)),
                ('nombres_normalizado', models.CharField(blank=True, max_length=240)),
                ('apellidos_bruto', models.CharField(blank=True, max_length=240)),
                ('apellidos_normalizado', models.CharField(blank=True, max_length=240)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('lugar_expedicion_bruto', models.CharField(blank=True, max_length=240)),
                ('lugar_expedicion_normalizado', models.CharField(blank=True, max_length=240)),
                ('confianza', models.JSONField(blank=True, default=dict)),
                ('evidencia', models.JSONField(blank=True, default=dict)),
                ('captura_frontal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion_creditos.capturadocumentoidentidad')),
                ('captura_trasera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion_creditos.capturadocumentoidentidad')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesamientos_ocr', to='gestion_creditos.sesioncapturadocumental')),
            ],
        ),
        migrations.CreateModel(
            name='ComparacionOCRDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_datos', models.CharField(max_length=64)),
                ('version_comparador', models.CharField(default='1', max_length=32)),
                ('snapshot', models.JSONField(default=dict)),
                ('resultados', models.JSONField(default=dict)),
                ('discrepancias', models.JSONField(default=list)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('vigente', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('libranza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_creditos.creditolibranza')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contractors.contractorapplication')),
                ('procesamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaciones', to='gestion_creditos.procesamientoocrdocumental')),
            ],
        ),
        migrations.AddField(
            model_name='eventocapturadocumental',
            name='procesamiento_ocr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='gestion_creditos.procesamientoocrdocumental'),
        ),
        migrations.AddIndex(
            model_name='procesamientoocrdocumental',
            index=models.Index(fields=['estado', 'reservado_hasta'], name='ocr_estado_reserva_idx'),
        ),
        migrations.AddConstraint(
            model_name='procesamientoocrdocumental',
            constraint=models.UniqueConstraint(fields=('sesion', 'captura_frontal', 'captura_trasera', 'firma_configuracion'), name='ocr_inputs_config_unicos'),
        ),
        migrations.AddConstraint(
            model_name='comparacionocrdocumental',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('libranza__isnull', False), ('solicitud__isnull', True)), models.Q(('libranza__isnull', True), ('solicitud__isnull', False)), _connector='OR'), name='ocr_comparacion_contexto'),
        ),
        migrations.AddConstraint(
            model_name='comparacionocrdocumental',
            constraint=models.UniqueConstraint(fields=('procesamiento', 'version_datos', 'version_comparador'), name='ocr_comparacion_version_unica'),
        ),
    ]
