# Generated by Django 5.2 on 2025-04-19 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=255)),
                ('nivel', models.CharField(max_length=255)),
                ('estimacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('numero_cedula', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField()),
                ('celular_wh', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('estado_civil', models.CharField(max_length=20)),
                ('numero_personas_cargo', models.IntegerField()),
                ('nombre_negocio', models.CharField(max_length=100)),
                ('ubicacion_negocio', models.TextField()),
                ('tiempo_operando', models.CharField(max_length=50)),
                ('dias_trabajados_sem', models.IntegerField()),
                ('prod_serv_ofrec', models.TextField()),
                ('ingresos_prom_mes', models.CharField(max_length=50)),
                ('cli_aten_day', models.IntegerField()),
                ('inventario', models.CharField(max_length=2)),
                ('nomb_ref_per1', models.CharField(max_length=100)),
                ('cel_ref_per1', models.CharField(max_length=20)),
                ('rel_ref_per1', models.CharField(max_length=50)),
                ('nomb_ref_cl1', models.CharField(max_length=100)),
                ('cel_ref_cl1', models.CharField(max_length=20)),
                ('rel_ref_cl1', models.CharField(max_length=50)),
                ('ref_conoc_lid_com', models.CharField(max_length=2)),
                ('foto_negocio', models.FileField(help_text='Solo se permiten archivos PDF', upload_to='fotos_negocios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('desc_fotos_neg', models.TextField()),
                ('tipo_cta_mno', models.CharField(max_length=20)),
                ('ahorro_tand_alc', models.CharField(max_length=2)),
                ('depend_h', models.CharField(max_length=2)),
                ('desc_cred_nec', models.TextField()),
                ('redes_soc', models.CharField(max_length=2)),
                ('fotos_prod', models.CharField(max_length=2)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
            ],
        ),
    ]
