# Generated by Django 5.2 on 2025-06-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
