# Generated by Django 5.2 on 2025-10-08 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('INVERSIONISTA', 'Inversionista'), ('EMPRENDEDOR', 'Emprendedor'), ('EMPLEADO', 'Empleado'), ('ADMIN', 'Administrador')], max_length=20)),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('acepta_terminos', models.BooleanField(default=False)),
                ('verificado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
