# Generated by Django 5.2 on 2026-06-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_executiveaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpagador',
            name='nivel_aprobacion_libranza',
            field=models.CharField(choices=[('NIVEL_1', 'Aprobador nivel 1'), ('FINAL', 'Aprobador final'), ('AMBOS', 'Ambos niveles')], default='AMBOS', help_text='Nivel de aprobacion de libranza que puede ejecutar este usuario pagador.', max_length=16),
        ),
    ]
