# Generated by Django 5.2 on 2026-06-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_executiveaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpagador',
            name='nivel_aprobacion_libranza',
            field=models.CharField(choices=[('NIVEL_1', 'Nivel 1'), ('FINAL', 'Final'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=20, verbose_name='Nivel aprobacion libranza'),
        ),
    ]
