# Generated by Django 5.2 on 2026-06-14 19:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaDatacreditoSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('servicio', models.CharField(choices=[('decisor', 'MiDecisor'), ('historial', 'Historia de Credito')], db_index=True, max_length=20)),
                ('ambiente', models.CharField(db_index=True, max_length=20)),
                ('proveedor', models.CharField(choices=[('datacredito_real', 'DataCredito real'), ('mock', 'Mock')], default='datacredito_real', max_length=40)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('request_fingerprint', models.CharField(db_index=True, max_length=128)),
                ('documento_hash', models.CharField(db_index=True, max_length=128)),
                ('documento_enmascarado', models.CharField(max_length=40)),
                ('estado_normalizado', models.CharField(db_index=True, max_length=80)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('codigo_funcional', models.CharField(blank=True, max_length=60)),
                ('proveedor_respondio', models.BooleanField(default=False)),
                ('consulta_procesada', models.BooleanField(default=False)),
                ('con_informacion', models.BooleanField(blank=True, null=True)),
                ('utilizable_para_score', models.BooleanField(default=False)),
                ('requiere_revision_manual', models.BooleanField(default=True)),
                ('requiere_revision_cumplimiento', models.BooleanField(default=False)),
                ('resultado_normalizado', models.JSONField(blank=True, default=dict)),
                ('consulted_at', models.DateTimeField(db_index=True)),
                ('vigente_hasta', models.DateTimeField(db_index=True)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('CONSULTA_REAL', 'Consulta real'), ('MOCK', 'Mock'), ('DIAGNOSTICO', 'Diagnostico')], db_index=True, default='CONSULTA_REAL', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_datacredito_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'snapshot DataCredito',
                'verbose_name_plural': 'snapshots DataCredito',
                'ordering': ('-consulted_at',),
                'permissions': (('can_force_datacredito_refresh', 'Puede forzar nueva consulta DataCredito'),),
                'indexes': [models.Index(fields=['ambiente', 'servicio', 'request_fingerprint', 'source', 'vigente_hasta'], name='datacred_snap_reuse_idx'), models.Index(fields=['documento_hash', 'consulted_at'], name='datacred_snap_doc_idx')],
            },
        ),
    ]
