# Generated by Django 5.2 on 2026-07-16 02:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaDatacreditoSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ambiente', models.CharField(db_index=True, max_length=16)),
                ('servicio', models.CharField(choices=[('decisor', 'MiDecisor'), ('historial', 'HDCPlus')], db_index=True, max_length=20)),
                ('documento_hash', models.CharField(db_index=True, max_length=64)),
                ('documento_enmascarado', models.CharField(max_length=32)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('EXITOSO', 'Exitoso'), ('SIN_INFORMACION', 'Sin información'), ('ERROR_TRANSITORIO', 'Error transitorio'), ('ERROR_PERMANENTE', 'Error permanente')], db_index=True, max_length=24)),
                ('resultado_normalizado', models.JSONField(blank=True, default=dict)),
                ('codigo_http', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('codigo_funcional', models.CharField(blank=True, max_length=60)),
                ('consultado_en', models.DateTimeField()),
                ('vigente_hasta', models.DateTimeField()),
                ('autorizacion_referencia', models.CharField(max_length=64)),
                ('error_codigo', models.CharField(blank=True, max_length=80)),
                ('error_tipo', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_datacredito_prestadores_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot DataCrédito',
                'verbose_name_plural': 'Snapshots DataCrédito',
                'db_table': 'integrations_consultadatacreditosnapshot_v2',
                'ordering': ['-consultado_en', '-created_at'],
                'permissions': [('can_force_datacredito_refresh', 'Puede forzar una consulta DataCrédito')],
                'indexes': [models.Index(fields=['ambiente', 'servicio', 'fingerprint', '-vigente_hasta'], name='datacred_v2_reuse_idx'), models.Index(fields=['documento_hash', '-consultado_en'], name='datacred_v2_documento_idx'), models.Index(fields=['estado', '-created_at'], name='datacred_v2_estado_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'EN_PROCESO')), fields=('fingerprint',), name='unique_datacredito_v2_en_proceso')],
            },
        ),
    ]
