# Generated by Django 5.2 on 2026-06-14 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultadatacreditosnapshot',
            name='autorizacion_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultadatacreditosnapshot',
            name='autorizacion_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='consultadatacreditosnapshot',
            name='autorizacion_texto_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='consultadatacreditosnapshot',
            name='autorizacion_version_texto',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='consultadatacreditosnapshot',
            index=models.Index(fields=['autorizacion_id'], name='datacred_snap_auth_idx'),
        ),
    ]
