# Generated by Django 5.2 on 2026-07-09 02:56

import contractors.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_creditos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escenario_credito', models.CharField(choices=[('NUEVO_CREDITO', 'Nuevo credito'), ('SEGUNDO_CREDITO', 'Segundo credito'), ('RECOGIDA_CARTERA', 'Recogida de cartera')], default='NUEVO_CREDITO', max_length=32)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria')], max_length=4)),
                ('numero_documento', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('celular', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=160)),
                ('fecha_inicio_contrato', models.DateField(blank=True, null=True)),
                ('fecha_fin_contrato', models.DateField(blank=True, null=True)),
                ('valor_total_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_pendiente_cobrar', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('DOCUMENTOS_PENDIENTES', 'Documentos pendientes'), ('DOCUMENTOS_CARGADOS', 'Documentos cargados')], default='DOCUMENTOS_PENDIENTES', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_prestadores', to='gestion_creditos.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_prestadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de prestador',
                'verbose_name_plural': 'Solicitudes de prestadores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CEDULA_FRONTAL', 'Cedula frontal'), ('CEDULA_TRASERA', 'Cedula trasera'), ('CONTRATO', 'Contrato vigente'), ('CERTIFICADO_BANCARIO', 'Certificado bancario')], max_length=32)),
                ('archivo', models.FileField(upload_to=contractors.models.ruta_documento_prestador)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contractors.contractorapplication')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_prestadores_cargados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de prestador',
                'verbose_name_plural': 'Documentos de prestadores',
                'ordering': ['tipo_documento'],
            },
        ),
        migrations.AddIndex(
            model_name='contractorapplication',
            index=models.Index(fields=['usuario', '-created_at'], name='prestador_usuario_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorapplication',
            index=models.Index(fields=['empresa', 'estado'], name='prestador_empresa_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorapplication',
            index=models.Index(fields=['numero_documento'], name='prestador_documento_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractorapplicationdocument',
            constraint=models.UniqueConstraint(fields=('solicitud', 'tipo_documento'), name='unique_documento_por_solicitud_prestador'),
        ),
    ]
