# Generated by Django 5.2 on 2026-07-12 20:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_solicitud_monto_plazo_estado_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorapplication',
            name='acepta_politica_privacidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='autoriza_analisis_contractual_asistido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='autoriza_consulta_centrales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='observaciones_contrato',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='tipo_contrato',
            field=models.CharField(choices=[('PRESTACION_SERVICIOS', 'Prestación de servicios'), ('LABORAL', 'Laboral'), ('OTRO', 'Otro')], default='PRESTACION_SERVICIOS', max_length=30),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='valor_pagado_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
