# Generated by Django 5.2 on 2026-07-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_contractorapplication_acepta_politica_privacidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorapplication',
            name='estado_analisis_contractual',
            field=models.CharField(choices=[('NO_SOLICITADO', 'No solicitado'), ('NO_DISPONIBLE', 'No disponible'), ('COMPLETADO', 'Completado'), ('CON_ADVERTENCIAS', 'Con advertencias'), ('BLOQUEADO', 'Bloqueado')], default='NO_SOLICITADO', max_length=24),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='fecha_analisis_contractual',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='metadata_analisis_contractual',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contractorapplicationdocument',
            name='metadata_captura',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
