# Generated by Django 5.2 on 2026-07-13 23:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_contractorapplication_estado_analisis_contractual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSimuladorPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(default='Simulador Prestadores', max_length=120)),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=Decimal('1000000'), max_digits=14)),
                ('monto_maximo', models.DecimalField(decimal_places=2, default=Decimal('10000000'), max_digits=14)),
                ('plazo_minimo_meses', models.PositiveSmallIntegerField(default=3)),
                ('plazo_maximo_meses', models.PositiveSmallIntegerField(default=24)),
                ('tasa_mensual', models.DecimalField(decimal_places=4, default=Decimal('1.9000'), help_text='Tasa efectiva mensual expresada como porcentaje. Ejemplo: 1.9.', max_digits=8)),
                ('porcentaje_originacion', models.DecimalField(decimal_places=4, default=Decimal('10.0000'), help_text='Porcentaje aplicado sobre el monto solicitado. Ejemplo: 10.', max_digits=8)),
                ('porcentaje_iva_originacion', models.DecimalField(decimal_places=4, default=Decimal('19.0000'), help_text='IVA sobre el costo de originación. Ejemplo: 19.', max_digits=8)),
                ('porcentaje_fondo_garantia', models.DecimalField(decimal_places=4, default=Decimal('2.0000'), help_text='Fondo de garantía, IVA incluido, sobre el monto solicitado.', max_digits=8)),
                ('porcentaje_seguro_vida_primera_cuota', models.DecimalField(decimal_places=4, default=Decimal('0.3711'), help_text='Seguro de vida de la primera cuota sobre el monto solicitado.', max_digits=8)),
                ('texto_nota_simulacion', models.TextField(blank=True, default='', help_text='Nota informativa opcional mostrada debajo de la simulación.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del simulador de prestadores',
                'verbose_name_plural': 'Configuraciones del simulador de prestadores',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
