# Generated by Django 5.2 on 2026-07-16 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0005_configuracionsimuladorprestador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorapplication',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('DOCUMENTOS_PENDIENTES', 'Documentos pendientes'), ('DOCUMENTOS_CARGADOS', 'Documentos cargados'), ('EVALUACION_PENDIENTE', 'Evaluación pendiente'), ('EN_EVALUACION', 'En evaluación'), ('EVALUACION_COMPLETADA', 'Evaluación completada'), ('EN_REVISION', 'En revisión manual')], default='DOCUMENTOS_PENDIENTES', max_length=32),
        ),
        migrations.CreateModel(
            name='PredecisionPrestadorAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_datos', models.CharField(max_length=64)),
                ('clave_idempotencia', models.CharField(max_length=64, unique=True)),
                ('estado_ejecucion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('ERROR_CONTROLADO', 'Error controlado')], default='PENDIENTE', max_length=24)),
                ('resultado', models.CharField(choices=[('NO_EVALUABLE', 'No evaluable'), ('REQUIERE_REVISION_MANUAL', 'Requiere revisión manual'), ('BLOQUEADO_READ_ONLY', 'Bloqueado read-only'), ('PREAPROBADO_READ_ONLY', 'Preaprobado read-only'), ('ERROR_CONTROLADO', 'Error controlado')], default='NO_EVALUABLE', max_length=32)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('version_score', models.CharField(blank=True, max_length=80)),
                ('version_politica', models.CharField(max_length=80)),
                ('razones', models.JSONField(blank=True, default=list)),
                ('alertas', models.JSONField(blank=True, default=list)),
                ('bloqueos', models.JSONField(blank=True, default=list)),
                ('snapshot_entrada', models.JSONField(blank=True, default=dict)),
                ('snapshot_salida', models.JSONField(blank=True, default=dict)),
                ('error_codigo', models.CharField(blank=True, max_length=80)),
                ('error_etapa', models.CharField(blank=True, max_length=80)),
                ('iniciada_en', models.DateTimeField()),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_predecision_prestador_creadas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_predecision', to='contractors.contractorapplication')),
            ],
            options={
                'verbose_name': 'Auditoría de predecisión de prestador',
                'verbose_name_plural': 'Auditorías de predecisión de prestadores',
                'db_table': 'contractors_predecisionprestadoraudit_v2',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['solicitud', '-created_at'], name='prest_audit_solic_fecha_idx'), models.Index(fields=['resultado'], name='prest_audit_resultado_idx'), models.Index(fields=['estado_ejecucion'], name='prest_audit_ejecucion_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimelinePrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('SOLICITUD_REGISTRADA', 'Solicitud registrada'), ('EVALUACION_PENDIENTE', 'Evaluación pendiente'), ('EVALUACION_INICIADA', 'Evaluación iniciada'), ('EVALUACION_COMPLETADA', 'Evaluación completada'), ('REVISION_MANUAL_REQUERIDA', 'Revisión manual requerida'), ('DATOS_MODIFICADOS', 'Datos modificados')], max_length=40)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visible_cliente', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_prestador_creado', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_operativo', to='contractors.contractorapplication')),
            ],
            options={
                'verbose_name': 'Evento de timeline de prestador',
                'verbose_name_plural': 'Timeline de prestadores',
                'db_table': 'contractors_timelineprestador_v2',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['solicitud', '-created_at'], name='prest_timeline_solic_idx'), models.Index(fields=['tipo_evento', '-created_at'], name='prest_timeline_tipo_idx')],
            },
        ),
    ]
