# Generated by Django 5.2 on 2026-07-16 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0006_alter_contractorapplication_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineprestador',
            name='tipo_evento',
            field=models.CharField(choices=[('SOLICITUD_REGISTRADA', 'Solicitud registrada'), ('EVALUACION_PENDIENTE', 'Evaluación pendiente'), ('EVALUACION_INICIADA', 'Evaluación iniciada'), ('EVALUACION_COMPLETADA', 'Evaluación completada'), ('REVISION_MANUAL_REQUERIDA', 'Revisión manual requerida'), ('DATOS_MODIFICADOS', 'Datos modificados'), ('DATACREDITO_REUTILIZADO', 'DataCrédito reutilizado'), ('DATACREDITO_CONSULTADO', 'DataCrédito consultado'), ('DATACREDITO_ERROR', 'Error DataCrédito')], max_length=40),
        ),
        migrations.CreateModel(
            name='AutorizacionConsultaDatacreditoPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizada', models.BooleanField()),
                ('version_texto', models.CharField(max_length=80)),
                ('texto_hash', models.CharField(max_length=64)),
                ('aceptada_en', models.DateTimeField()),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_datacredito', to='contractors.contractorapplication')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_datacredito_prestador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autorización DataCrédito de prestador',
                'verbose_name_plural': 'Autorizaciones DataCrédito de prestadores',
                'db_table': 'contractors_autorizaciondatacredito_v2',
                'ordering': ['-aceptada_en', '-id'],
                'indexes': [models.Index(fields=['solicitud', '-aceptada_en'], name='prest_auth_dc_solic_idx'), models.Index(fields=['version_texto', 'texto_hash'], name='prest_auth_dc_version_idx')],
                'constraints': [models.UniqueConstraint(fields=('solicitud', 'usuario', 'autorizada', 'version_texto', 'texto_hash'), name='unique_autorizacion_datacredito_v2')],
            },
        ),
    ]
