# Generated by Django 5.2 on 2026-07-17 22:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0007_alter_timelineprestador_tipo_evento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandaScorePrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PREMIUM', 'Premium'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('ENTRADA', 'Entrada'), ('REVISION', 'Revision')], max_length=16)),
                ('score_min', models.PositiveSmallIntegerField()),
                ('score_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('monto_maximo', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('plazo_maximo', models.PositiveSmallIntegerField(default=0)),
                ('resultado', models.CharField(choices=[('PREAPROBADO_READ_ONLY', 'Preaprobado read-only'), ('REQUIERE_REVISION_MANUAL', 'Requiere revision manual')], max_length=32)),
                ('orden', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Banda de score de prestadores',
                'verbose_name_plural': 'Bandas de score de prestadores',
                'ordering': ['orden', '-score_min'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionScorePrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=80, unique=True)),
                ('activa', models.BooleanField(default=False)),
                ('fecha_vigencia_desde', models.DateField()),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('peso_datacredito', models.DecimalField(decimal_places=5, max_digits=6)),
                ('peso_capacidad', models.DecimalField(decimal_places=5, max_digits=6)),
                ('peso_comportamiento', models.DecimalField(decimal_places=5, max_digits=6)),
                ('peso_riesgo', models.DecimalField(decimal_places=5, max_digits=6)),
                ('peso_referencias', models.DecimalField(decimal_places=5, max_digits=6)),
                ('score_premium_min', models.PositiveSmallIntegerField(default=850)),
                ('score_alta_min', models.PositiveSmallIntegerField(default=750)),
                ('score_media_min', models.PositiveSmallIntegerField(default=680)),
                ('score_entrada_min', models.PositiveSmallIntegerField(default=600)),
                ('cuota_ingreso_maxima', models.DecimalField(decimal_places=5, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('monto_maximo_politica', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('plazo_maximo_politica', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tasa_mensual_referencia', models.DecimalField(decimal_places=4, help_text='Porcentaje mensual de referencia. Ejemplo: 2.2000.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('penalizacion_geolocalizacion', models.PositiveSmallIntegerField(default=80)),
                ('umbral_geolocalizacion', models.PositiveSmallIntegerField(default=600)),
                ('mora_bloqueo_dias', models.PositiveSmallIntegerField(default=90)),
                ('consultas_recientes_revision', models.PositiveSmallIntegerField(default=6)),
                ('requiere_referencias', models.BooleanField(default=False)),
                ('permite_redistribuir_pesos_faltantes', models.BooleanField(default=False)),
                ('accion_exceso_capacidad', models.CharField(choices=[('BLOQUEAR', 'Bloquear en modo read-only'), ('REVISION', 'Enviar a revision manual')], default='REVISION', max_length=16)),
                ('version_score', models.CharField(max_length=80)),
                ('version_politica', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de score de prestadores',
                'verbose_name_plural': 'Configuraciones de score de prestadores',
                'ordering': ['-fecha_vigencia_desde', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='predecisionprestadoraudit',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('can_evaluate_contractor_application', 'Puede ejecutar la evaluacion formal de prestadores')], 'verbose_name': 'Auditoría de predecisión de prestador', 'verbose_name_plural': 'Auditorías de predecisión de prestadores'},
        ),
        migrations.AddField(
            model_name='configuracionsimuladorprestador',
            name='version',
            field=models.CharField(blank=True, help_text='Version administrativa de la configuracion financiera.', max_length=80),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='duracion_contrato_meses',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Duracion contractual explicita en meses calendario.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='estado_contractual_declarado',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('SUSPENDIDO', 'Suspendido'), ('TERMINADO', 'Terminado'), ('LIQUIDADO', 'Liquidado'), ('NO_DETERMINABLE', 'No determinable')], default='NO_DETERMINABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='monto_maximo_configuracion_simulacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='monto_simulado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='plazo_maximo_configuracion_simulacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='plazo_simulado_meses',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='simulada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='tasa_mensual_simulacion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='version_configuracion_financiera_simulacion',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='version_politica_simulacion',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='monto_maximo_configuracion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='plazo_maximo_configuracion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='tasa_mensual_configuracion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='version_configuracion_financiera',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name='configuracionsimuladorprestador',
            constraint=models.UniqueConstraint(condition=models.Q(('version', ''), _negated=True), fields=('version',), name='unique_simulador_prestador_version'),
        ),
        migrations.AddField(
            model_name='configuracionscoreprestador',
            name='configuracion_financiera',
            field=models.ForeignKey(blank=True, help_text='Configuracion financiera exacta aplicable a esta politica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='politicas_score', to='contractors.configuracionsimuladorprestador'),
        ),
        migrations.AddField(
            model_name='bandascoreprestador',
            name='configuracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bandas', to='contractors.configuracionscoreprestador'),
        ),
        migrations.AddConstraint(
            model_name='configuracionscoreprestador',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('activa',), name='unique_score_prestador_activo'),
        ),
        migrations.AddConstraint(
            model_name='bandascoreprestador',
            constraint=models.UniqueConstraint(fields=('configuracion', 'nombre'), name='unique_banda_score_prestador_nombre'),
        ),
        migrations.AddConstraint(
            model_name='bandascoreprestador',
            constraint=models.UniqueConstraint(fields=('configuracion', 'orden'), name='unique_banda_score_prestador_orden'),
        ),
        migrations.AddConstraint(
            model_name='bandascoreprestador',
            constraint=models.CheckConstraint(condition=models.Q(('score_min__lte', 1000)), name='banda_score_prestador_min_lte_1000'),
        ),
        migrations.AddConstraint(
            model_name='bandascoreprestador',
            constraint=models.CheckConstraint(condition=models.Q(('score_max__isnull', True), ('score_max__lte', 1000), _connector='OR'), name='banda_score_prestador_max_lte_1000'),
        ),
    ]
