# Generated by Django 5.2 on 2026-07-18 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0008_bandascoreprestador_configuracionscoreprestador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineprestador',
            name='tipo_evento',
            field=models.CharField(choices=[('SOLICITUD_REGISTRADA', 'Solicitud registrada'), ('EVALUACION_PENDIENTE', 'Evaluación pendiente'), ('EVALUACION_INICIADA', 'Evaluación iniciada'), ('EVALUACION_COMPLETADA', 'Evaluación completada'), ('REVISION_MANUAL_REQUERIDA', 'Revisión manual requerida'), ('DATOS_MODIFICADOS', 'Datos modificados'), ('DATACREDITO_REUTILIZADO', 'DataCrédito reutilizado'), ('DATACREDITO_CONSULTADO', 'DataCrédito consultado'), ('DATACREDITO_ERROR', 'Error DataCrédito'), ('REVISION_CREADA', 'Revision creada'), ('REVISION_ASIGNADA', 'Revision asignada'), ('REVISION_INICIADA', 'Revision iniciada'), ('SUBSANACION_SOLICITADA', 'Subsanacion solicitada'), ('SUBSANACION_ATENDIDA', 'Subsanacion atendida'), ('VALIDACION_EMPRESA_SOLICITADA', 'Validacion de empresa solicitada'), ('EVALUACION_REINTENTADA', 'Evaluacion reintentada'), ('REVISION_RESUELTA', 'Revision resuelta'), ('REVISION_CANCELADA', 'Revision cancelada')], max_length=40),
        ),
        migrations.CreateModel(
            name='RevisionManualPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('ASIGNADA', 'Asignada'), ('EN_ANALISIS', 'En analisis'), ('PENDIENTE_SOLICITANTE', 'Pendiente del solicitante'), ('PENDIENTE_VALIDACION_EMPRESA', 'Pendiente de validacion de empresa'), ('RESUELTA', 'Resuelta'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=36)),
                ('motivo', models.CharField(choices=[('CONTRATO_NO_DETERMINABLE', 'Contrato no determinable'), ('CONTRATO_SUSPENDIDO', 'Contrato suspendido'), ('CONTRATO_VENCIDO', 'Contrato vencido'), ('DOCUMENTOS_INCOMPLETOS', 'Documentos incompletos'), ('IDENTIDAD_INCONSISTENTE', 'Identidad inconsistente'), ('CAPACIDAD_NO_DETERMINABLE', 'Capacidad no determinable'), ('CAPACIDAD_EXCEDIDA', 'Capacidad excedida'), ('DATACREDITO_NO_DISPONIBLE', 'Validacion externa no disponible'), ('DATACREDITO_ERROR', 'Error de validacion externa'), ('DATOS_MODIFICADOS', 'Datos modificados'), ('POLITICA_INCOMPATIBLE', 'Politica incompatible'), ('VALIDACION_EMPRESA_REQUERIDA', 'Validacion de empresa requerida'), ('OTRA_REVISION_CONTROLADA', 'Otra revision controlada')], max_length=40)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], default='MEDIA', max_length=12)),
                ('comentario_interno', models.TextField(blank=True)),
                ('resultado', models.CharField(blank=True, choices=[('CONTINUAR_EVALUACION', 'Continuar evaluacion'), ('SOLICITAR_NUEVO_CONTRATO', 'Solicitar nuevo contrato'), ('SOLICITAR_DOCUMENTO', 'Solicitar documento'), ('SOLICITAR_CORRECCION_INFORMACION', 'Solicitar correccion de informacion'), ('SOLICITAR_VALIDACION_EMPRESA', 'Solicitar validacion de empresa'), ('MANTENER_BLOQUEO', 'Mantener bloqueo'), ('CERRAR_SIN_CONTINUAR', 'Cerrar sin continuar')], max_length=44)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('asignada_en', models.DateTimeField(blank=True, null=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_prestador_asignadas', to=settings.AUTH_USER_MODEL)),
                ('auditoria_predecision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_manuales', to='contractors.predecisionprestadoraudit')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_prestador_creadas', to=settings.AUTH_USER_MODEL)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_prestador_resueltas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_manuales', to='contractors.contractorapplication')),
            ],
            options={
                'verbose_name': 'Revision manual de prestador',
                'verbose_name_plural': 'Revisiones manuales de prestadores',
                'ordering': ['-creada_en', '-id'],
                'permissions': [('can_view_contractor_review_queue', 'Puede ver la bandeja de revision de prestadores'), ('can_assign_contractor_review', 'Puede asignar revisiones de prestadores'), ('can_resolve_contractor_review', 'Puede resolver revisiones de prestadores'), ('can_request_contractor_correction', 'Puede solicitar correcciones a prestadores'), ('can_view_contractor_score_details', 'Puede ver el detalle de score de prestadores')],
            },
        ),
        migrations.CreateModel(
            name='RequerimientoSubsanacionPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NUEVO_CONTRATO', 'Nuevo contrato'), ('ACTUALIZAR_CONTRATO', 'Actualizar contrato'), ('DOCUMENTO_IDENTIDAD', 'Documento de identidad'), ('DOCUMENTO_CONTRACTUAL', 'Documento contractual'), ('CERTIFICACION_BANCARIA', 'Certificacion bancaria'), ('INFORMACION_CONTRACTUAL', 'Informacion contractual'), ('INFORMACION_PERSONAL', 'Informacion personal')], max_length=32)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDO', 'Atendido'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=12)),
                ('mensaje_publico', models.CharField(max_length=500)),
                ('detalle_interno', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('atendido_en', models.DateTimeField(blank=True, null=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsanaciones_prestador_creadas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_subsanacion', to='contractors.contractorapplication')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_subsanacion', to='contractors.revisionmanualprestador')),
            ],
            options={
                'verbose_name': 'Requerimiento de subsanacion de prestador',
                'verbose_name_plural': 'Requerimientos de subsanacion de prestadores',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='revisionmanualprestador',
            index=models.Index(fields=['estado', 'prioridad', '-creada_en'], name='prest_rev_estado_prio_idx'),
        ),
        migrations.AddIndex(
            model_name='revisionmanualprestador',
            index=models.Index(fields=['solicitud', '-creada_en'], name='prest_rev_solic_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='revisionmanualprestador',
            index=models.Index(fields=['asignado_a', 'estado'], name='prest_rev_asignado_idx'),
        ),
        migrations.AddConstraint(
            model_name='revisionmanualprestador',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['ABIERTA', 'ASIGNADA', 'EN_ANALISIS', 'PENDIENTE_SOLICITANTE', 'PENDIENTE_VALIDACION_EMPRESA'])), fields=('solicitud', 'motivo'), name='unique_revision_activa_solic_motivo'),
        ),
        migrations.AddIndex(
            model_name='requerimientosubsanacionprestador',
            index=models.Index(fields=['solicitud', 'estado'], name='prest_subsan_solic_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='requerimientosubsanacionprestador',
            index=models.Index(fields=['revision', '-creado_en'], name='prest_subsan_revision_idx'),
        ),
        migrations.AddConstraint(
            model_name='requerimientosubsanacionprestador',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('solicitud', 'tipo'), name='unique_subsanacion_pendiente_tipo'),
        ),
    ]
