# Generated by Django 5.2 on 2026-07-18 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0009_alter_timelineprestador_tipo_evento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineprestador',
            name='tipo_evento',
            field=models.CharField(choices=[('SOLICITUD_REGISTRADA', 'Solicitud registrada'), ('EVALUACION_PENDIENTE', 'Evaluación pendiente'), ('EVALUACION_INICIADA', 'Evaluación iniciada'), ('EVALUACION_COMPLETADA', 'Evaluación completada'), ('REVISION_MANUAL_REQUERIDA', 'Revisión manual requerida'), ('DATOS_MODIFICADOS', 'Datos modificados'), ('DATACREDITO_REUTILIZADO', 'DataCrédito reutilizado'), ('DATACREDITO_CONSULTADO', 'DataCrédito consultado'), ('DATACREDITO_ERROR', 'Error DataCrédito'), ('REVISION_CREADA', 'Revision creada'), ('REVISION_ASIGNADA', 'Revision asignada'), ('REVISION_INICIADA', 'Revision iniciada'), ('SUBSANACION_SOLICITADA', 'Subsanacion solicitada'), ('SUBSANACION_ATENDIDA', 'Subsanacion atendida'), ('VALIDACION_EMPRESA_SOLICITADA', 'Validacion de empresa solicitada'), ('EVALUACION_REINTENTADA', 'Evaluacion reintentada'), ('REVISION_RESUELTA', 'Revision resuelta'), ('REVISION_CANCELADA', 'Revision cancelada'), ('APROBACION_INTERNA_CREADA', 'Aprobacion interna creada'), ('APROBACION_INTERNA_INICIADA', 'Aprobacion interna iniciada'), ('APROBADA_PARA_ORIGINAR', 'Aprobada para originar'), ('DEVUELTA_A_REVISION', 'Devuelta a revision'), ('CERRADA_SIN_ORIGINAR', 'Cerrada sin originar'), ('APROBACION_INTERNA_CANCELADA', 'Aprobacion interna cancelada')], max_length=40),
        ),
        migrations.CreateModel(
            name='AprobacionInternaPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_ANALISIS', 'En analisis'), ('APROBADA_PARA_ORIGINAR', 'Aprobada para originar'), ('DEVUELTA_A_REVISION', 'Devuelta a revision'), ('CERRADA_SIN_ORIGINAR', 'Cerrada sin originar'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=28)),
                ('decision', models.CharField(blank=True, choices=[('APROBAR_PARA_ORIGINAR', 'Aprobar para originar'), ('DEVOLVER_A_REVISION', 'Devolver a revision'), ('CERRAR_SIN_ORIGINAR', 'Cerrar sin originar'), ('CANCELAR', 'Cancelar')], max_length=28)),
                ('motivo', models.CharField(blank=True, choices=[('DATOS_MODIFICADOS', 'Datos modificados'), ('CONTRATO_NO_VIGENTE', 'Contrato no vigente'), ('EMPRESA_SIN_CONVENIO', 'Empresa sin convenio activo'), ('POLITICA_CAMBIO', 'Cambio de politica'), ('CONFIGURACION_FINANCIERA_CAMBIO', 'Cambio de configuracion financiera'), ('SIMULACION_INVALIDA', 'Simulacion no vigente'), ('AUTORIZACION_NO_VIGENTE', 'Autorizacion DataCredito no vigente'), ('SNAPSHOT_NO_VIGENTE', 'Snapshot DataCredito no vigente'), ('REVISION_ACTIVA', 'Revision manual activa'), ('SUBSANACION_PENDIENTE', 'Subsanacion pendiente'), ('CIERRE_OPERATIVO', 'Cierre operativo'), ('CANCELACION_ADMINISTRATIVA', 'Cancelacion administrativa'), ('OTRA_VALIDACION_CONTROLADA', 'Otra validacion controlada')], max_length=40)),
                ('comentario_interno', models.TextField(blank=True)),
                ('version_datos', models.CharField(max_length=64)),
                ('version_politica', models.CharField(max_length=80)),
                ('version_configuracion_financiera', models.CharField(max_length=80)),
                ('tasa_mensual_snapshot', models.DecimalField(decimal_places=4, max_digits=8)),
                ('monto_solicitado_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_maximo_score_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monto_maximo_politica_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_maximo_capacidad_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monto_maximo_contrato_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_maximo_financiero_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_maximo_evaluado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_autorizado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('plazo_solicitado_snapshot', models.PositiveSmallIntegerField()),
                ('plazo_maximo_score_snapshot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plazo_maximo_politica_snapshot', models.PositiveSmallIntegerField()),
                ('plazo_maximo_contrato_snapshot', models.PositiveSmallIntegerField()),
                ('plazo_maximo_financiero_snapshot', models.PositiveSmallIntegerField()),
                ('plazo_maximo_evaluado', models.PositiveSmallIntegerField()),
                ('plazo_autorizado', models.PositiveSmallIntegerField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('decidida_en', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditoria_predecision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones_internas', to='contractors.predecisionprestadoraudit')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_internas_prestador_creadas', to=settings.AUTH_USER_MODEL)),
                ('decidida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_internas_prestador_decididas', to=settings.AUTH_USER_MODEL)),
                ('revision_manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones_internas', to='contractors.revisionmanualprestador')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones_internas', to='contractors.contractorapplication')),
            ],
            options={
                'verbose_name': 'Aprobacion interna de prestador',
                'verbose_name_plural': 'Aprobaciones internas de prestadores',
                'ordering': ['-creada_en', '-id'],
                'permissions': [('can_view_contractor_internal_approval', 'Puede ver aprobaciones internas de prestadores'), ('can_decide_contractor_internal_approval', 'Puede decidir aprobaciones internas de prestadores'), ('can_close_contractor_internal_approval', 'Puede cerrar aprobaciones internas de prestadores')],
                'indexes': [models.Index(fields=['estado', '-creada_en'], name='prest_aprob_estado_idx'), models.Index(fields=['solicitud', '-creada_en'], name='prest_aprob_solic_idx'), models.Index(fields=['decidida_por', '-decidida_en'], name='prest_aprob_actor_idx')],
                'constraints': [models.UniqueConstraint(fields=('auditoria_predecision',), name='unique_aprobacion_interna_auditoria'), models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'EN_ANALISIS', 'APROBADA_PARA_ORIGINAR'])), fields=('solicitud',), name='unique_aprobacion_interna_activa')],
            },
        ),
    ]
