# Generated by Django 5.2 on 2026-07-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0010_alter_timelineprestador_tipo_evento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprobacioninternaprestador',
            options={'ordering': ['-creada_en', '-id'], 'permissions': [('can_view_contractor_internal_approval', 'Puede ver aprobaciones internas de prestadores'), ('can_decide_contractor_internal_approval', 'Puede decidir aprobaciones internas de prestadores'), ('can_close_contractor_internal_approval', 'Puede cerrar aprobaciones internas de prestadores'), ('can_originate_contractor_credit', 'Puede originar creditos de prestadores aprobados internamente')], 'verbose_name': 'Aprobacion interna de prestador', 'verbose_name_plural': 'Aprobaciones internas de prestadores'},
        ),
        migrations.AlterField(
            model_name='timelineprestador',
            name='tipo_evento',
            field=models.CharField(choices=[('SOLICITUD_REGISTRADA', 'Solicitud registrada'), ('EVALUACION_PENDIENTE', 'Evaluación pendiente'), ('EVALUACION_INICIADA', 'Evaluación iniciada'), ('EVALUACION_COMPLETADA', 'Evaluación completada'), ('REVISION_MANUAL_REQUERIDA', 'Revisión manual requerida'), ('DATOS_MODIFICADOS', 'Datos modificados'), ('DATACREDITO_REUTILIZADO', 'DataCrédito reutilizado'), ('DATACREDITO_CONSULTADO', 'DataCrédito consultado'), ('DATACREDITO_ERROR', 'Error DataCrédito'), ('REVISION_CREADA', 'Revision creada'), ('REVISION_ASIGNADA', 'Revision asignada'), ('REVISION_INICIADA', 'Revision iniciada'), ('SUBSANACION_SOLICITADA', 'Subsanacion solicitada'), ('SUBSANACION_ATENDIDA', 'Subsanacion atendida'), ('VALIDACION_EMPRESA_SOLICITADA', 'Validacion de empresa solicitada'), ('EVALUACION_REINTENTADA', 'Evaluacion reintentada'), ('REVISION_RESUELTA', 'Revision resuelta'), ('REVISION_CANCELADA', 'Revision cancelada'), ('APROBACION_INTERNA_CREADA', 'Aprobacion interna creada'), ('APROBACION_INTERNA_INICIADA', 'Aprobacion interna iniciada'), ('APROBADA_PARA_ORIGINAR', 'Aprobada para originar'), ('DEVUELTA_A_REVISION', 'Devuelta a revision'), ('CERRADA_SIN_ORIGINAR', 'Cerrada sin originar'), ('APROBACION_INTERNA_CANCELADA', 'Aprobacion interna cancelada'), ('ORIGINACION_INICIADA', 'Originacion iniciada'), ('ORIGINACION_COMPLETADA', 'Originacion completada'), ('ORIGINACION_REUTILIZADA', 'Originacion reutilizada'), ('ORIGINACION_ERROR_CONTROLADO', 'Error controlado de originacion')], max_length=40),
        ),
    ]
