# Generated by Django 5.2 on 2026-07-18 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0011_alter_aprobacioninternaprestador_options_and_more'),
        ('gestion_creditos', '0035_secuencianumerocredito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineprestador',
            name='tipo_evento',
            field=models.CharField(choices=[('SOLICITUD_REGISTRADA', 'Solicitud registrada'), ('EVALUACION_PENDIENTE', 'Evaluación pendiente'), ('EVALUACION_INICIADA', 'Evaluación iniciada'), ('EVALUACION_COMPLETADA', 'Evaluación completada'), ('REVISION_MANUAL_REQUERIDA', 'Revisión manual requerida'), ('DATOS_MODIFICADOS', 'Datos modificados'), ('DATACREDITO_REUTILIZADO', 'DataCrédito reutilizado'), ('DATACREDITO_CONSULTADO', 'DataCrédito consultado'), ('DATACREDITO_ERROR', 'Error DataCrédito'), ('REVISION_CREADA', 'Revision creada'), ('REVISION_ASIGNADA', 'Revision asignada'), ('REVISION_INICIADA', 'Revision iniciada'), ('SUBSANACION_SOLICITADA', 'Subsanacion solicitada'), ('SUBSANACION_ATENDIDA', 'Subsanacion atendida'), ('VALIDACION_EMPRESA_SOLICITADA', 'Validacion de empresa solicitada'), ('EVALUACION_REINTENTADA', 'Evaluacion reintentada'), ('REVISION_RESUELTA', 'Revision resuelta'), ('REVISION_CANCELADA', 'Revision cancelada'), ('APROBACION_INTERNA_CREADA', 'Aprobacion interna creada'), ('APROBACION_INTERNA_INICIADA', 'Aprobacion interna iniciada'), ('APROBADA_PARA_ORIGINAR', 'Aprobada para originar'), ('DEVUELTA_A_REVISION', 'Devuelta a revision'), ('CERRADA_SIN_ORIGINAR', 'Cerrada sin originar'), ('APROBACION_INTERNA_CANCELADA', 'Aprobacion interna cancelada'), ('ORIGINACION_INICIADA', 'Originacion iniciada'), ('ORIGINACION_COMPLETADA', 'Originacion completada'), ('ORIGINACION_REUTILIZADA', 'Originacion reutilizada'), ('ORIGINACION_ERROR_CONTROLADO', 'Error controlado de originacion'), ('FORMALIZACION_INICIADA', 'Formalizacion iniciada'), ('PAGARE_GENERADO', 'Pagare generado'), ('IDENTIDAD_VALIDADA_FIRMA', 'Identidad validada para firma'), ('ENVIO_FIRMA_INICIADO', 'Envio a firma iniciado'), ('PENDIENTE_FIRMA', 'Pendiente de firma'), ('FIRMA_CONFIRMADA', 'Firma confirmada'), ('FIRMA_ERROR_CONTROLADO', 'Error controlado de firma'), ('FORMALIZACION_REUTILIZADA', 'Formalizacion reutilizada')], max_length=40),
        ),
        migrations.CreateModel(
            name='FormalizacionCreditoPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARANDO_DOCUMENTO', 'Preparando documento'), ('DOCUMENTO_GENERADO', 'Documento generado'), ('PENDIENTE_VALIDACION_IDENTIDAD', 'Pendiente de validacion de identidad'), ('IDENTIDAD_VALIDADA', 'Identidad validada'), ('ENVIANDO_A_FIRMA', 'Enviando a firma'), ('PENDIENTE_FIRMA', 'Pendiente de firma'), ('FIRMADO', 'Firmado'), ('ERROR_CONTROLADO', 'Error controlado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=40)),
                ('clave_idempotencia', models.CharField(max_length=220, unique=True)),
                ('version_origen', models.CharField(max_length=64)),
                ('proveedor_firma', models.CharField(default='ZAPSIGN', max_length=30)),
                ('proveedor_document_id_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('estado_identidad', models.CharField(choices=[('IDENTIDAD_PENDIENTE', 'Identidad pendiente'), ('IDENTIDAD_VALIDADA', 'Identidad validada'), ('IDENTIDAD_EXPIRADA', 'Identidad expirada'), ('IDENTIDAD_FALLIDA', 'Identidad fallida')], default='IDENTIDAD_PENDIENTE', max_length=28)),
                ('identidad_referencia_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('identidad_validada_en', models.DateTimeField(blank=True, null=True)),
                ('identidad_expira_en', models.DateTimeField(blank=True, null=True)),
                ('intentos_firma', models.PositiveSmallIntegerField(default=0)),
                ('enviada_firma_en', models.DateTimeField(blank=True, null=True)),
                ('firmada_en', models.DateTimeField(blank=True, null=True)),
                ('error_codigo', models.CharField(blank=True, max_length=80)),
                ('error_etapa', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formalizaciones_prestador_creadas', to=settings.AUTH_USER_MODEL)),
                ('credito', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='formalizacion_prestador', to='gestion_creditos.credito')),
                ('credito_libranza', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='formalizacion_prestador', to='gestion_creditos.creditolibranza')),
                ('identidad_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identidades_firma_prestador', to=settings.AUTH_USER_MODEL)),
                ('origen_credito_prestador', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='formalizacion_prestador', to='gestion_creditos.origencreditoprestador')),
                ('pagare', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formalizacion_prestador', to='gestion_creditos.pagare')),
            ],
            options={
                'verbose_name': 'Formalizacion de credito de prestador',
                'verbose_name_plural': 'Formalizaciones de creditos de prestadores',
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_prepare_contractor_formalization', 'Puede preparar formalizaciones de prestadores'), ('can_retry_contractor_signature', 'Puede reintentar firmas de prestadores'), ('can_view_contractor_formalization', 'Puede ver formalizaciones de prestadores')],
                'indexes': [models.Index(fields=['estado', '-created_at'], name='prest_form_estado_idx'), models.Index(fields=['estado_identidad', '-created_at'], name='prest_form_ident_idx')],
            },
        ),
    ]
