# Generated by Django 5.2 on 2026-06-09 03:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0011_contractorapplication_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredecisionPrestadorAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escenario_credito', models.CharField(max_length=30)),
                ('decision', models.CharField(max_length=40)),
                ('eligible', models.BooleanField(default=False)),
                ('requiere_revision_manual', models.BooleanField(default=False)),
                ('monto_maximo_sugerido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('plazo_maximo_sugerido', models.PositiveSmallIntegerField(default=0)),
                ('score_status', models.CharField(blank=True, max_length=40)),
                ('score_final', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('score_banda', models.CharField(blank=True, max_length=40)),
                ('score_version_configuracion', models.CharField(blank=True, max_length=80)),
                ('datacredito_status', models.CharField(blank=True, max_length=40)),
                ('datacredito_fuente', models.CharField(blank=True, max_length=60)),
                ('datacredito_mora_severa', models.BooleanField(default=False)),
                ('datacredito_mora_actual', models.BooleanField(default=False)),
                ('capacidad_status', models.CharField(blank=True, max_length=40)),
                ('riesgo_status', models.CharField(blank=True, max_length=40)),
                ('bloqueos', models.JSONField(blank=True, default=list)),
                ('advertencias', models.JSONField(blank=True, default=list)),
                ('razones', models.JSONField(blank=True, default=list)),
                ('resultado_sanitizado', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_predecision', to='contractors.contractorapplication')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_predecision_prestador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de predecision prestador',
                'verbose_name_plural': 'Auditorias de predecision prestador',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['solicitud', 'created_at'], name='predec_audit_solicitud_idx'), models.Index(fields=['decision', 'created_at'], name='predec_audit_decision_idx'), models.Index(fields=['datacredito_status'], name='predec_audit_datacred_idx'), models.Index(fields=['score_banda'], name='predec_audit_score_idx')],
            },
        ),
    ]
