# Generated by Django 5.2 on 2026-07-18 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0012_alter_timelineprestador_tipo_evento_and_more'),
        ('gestion_creditos', '0035_secuencianumerocredito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineprestador',
            name='tipo_evento',
            field=models.CharField(choices=[('SOLICITUD_REGISTRADA', 'Solicitud registrada'), ('EVALUACION_PENDIENTE', 'Evaluación pendiente'), ('EVALUACION_INICIADA', 'Evaluación iniciada'), ('EVALUACION_COMPLETADA', 'Evaluación completada'), ('REVISION_MANUAL_REQUERIDA', 'Revisión manual requerida'), ('DATOS_MODIFICADOS', 'Datos modificados'), ('DATACREDITO_REUTILIZADO', 'DataCrédito reutilizado'), ('DATACREDITO_CONSULTADO', 'DataCrédito consultado'), ('DATACREDITO_ERROR', 'Error DataCrédito'), ('REVISION_CREADA', 'Revision creada'), ('REVISION_ASIGNADA', 'Revision asignada'), ('REVISION_INICIADA', 'Revision iniciada'), ('SUBSANACION_SOLICITADA', 'Subsanacion solicitada'), ('SUBSANACION_ATENDIDA', 'Subsanacion atendida'), ('VALIDACION_EMPRESA_SOLICITADA', 'Validacion de empresa solicitada'), ('EVALUACION_REINTENTADA', 'Evaluacion reintentada'), ('REVISION_RESUELTA', 'Revision resuelta'), ('REVISION_CANCELADA', 'Revision cancelada'), ('APROBACION_INTERNA_CREADA', 'Aprobacion interna creada'), ('APROBACION_INTERNA_INICIADA', 'Aprobacion interna iniciada'), ('APROBADA_PARA_ORIGINAR', 'Aprobada para originar'), ('DEVUELTA_A_REVISION', 'Devuelta a revision'), ('CERRADA_SIN_ORIGINAR', 'Cerrada sin originar'), ('APROBACION_INTERNA_CANCELADA', 'Aprobacion interna cancelada'), ('ORIGINACION_INICIADA', 'Originacion iniciada'), ('ORIGINACION_COMPLETADA', 'Originacion completada'), ('ORIGINACION_REUTILIZADA', 'Originacion reutilizada'), ('ORIGINACION_ERROR_CONTROLADO', 'Error controlado de originacion'), ('FORMALIZACION_INICIADA', 'Formalizacion iniciada'), ('PAGARE_GENERADO', 'Pagare generado'), ('IDENTIDAD_VALIDADA_FIRMA', 'Identidad validada para firma'), ('ENVIO_FIRMA_INICIADO', 'Envio a firma iniciado'), ('PENDIENTE_FIRMA', 'Pendiente de firma'), ('FIRMA_CONFIRMADA', 'Firma confirmada'), ('FIRMA_ERROR_CONTROLADO', 'Error controlado de firma'), ('FORMALIZACION_REUTILIZADA', 'Formalizacion reutilizada'), ('NOVEDAD_OPERATIVA_GENERADA', 'Novedad operativa generada'), ('NOVEDAD_OPERATIVA_ENVIO_INICIADO', 'Envio de novedad operativa iniciado'), ('NOVEDAD_OPERATIVA_ENVIADA', 'Novedad operativa enviada'), ('NOVEDAD_OPERATIVA_RECIBIDA', 'Novedad operativa recibida'), ('NOVEDAD_OPERATIVA_GESTIONADA', 'Novedad operativa gestionada'), ('NOVEDAD_OPERATIVA_ERROR', 'Error de novedad operativa'), ('NOVEDAD_OPERATIVA_REENVIO', 'Reenvio de novedad operativa')], max_length=40),
        ),
        migrations.CreateModel(
            name='NovedadOperativaPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_idempotencia', models.CharField(max_length=220, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE_ENVIO', 'Pendiente de envio'), ('ENVIANDO', 'Enviando'), ('ENVIADA', 'Enviada'), ('RECIBIDA', 'Recibida'), ('GESTIONADA', 'Gestionada'), ('ERROR_CONTROLADO', 'Error controlado'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_ENVIO', max_length=24)),
                ('tipo_novedad', models.CharField(choices=[('CREDITO_PRESTADOR_FORMALIZADO', 'Credito de prestador formalizado')], default='CREDITO_PRESTADOR_FORMALIZADO', max_length=40)),
                ('canal_envio', models.CharField(choices=[('EMAIL', 'Correo electronico')], default='EMAIL', max_length=20)),
                ('intentos_envio', models.PositiveSmallIntegerField(default=0)),
                ('destinatarios_hash', models.JSONField(blank=True, default=list)),
                ('destinatarios_enmascarados', models.JSONField(blank=True, default=list)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('recibida_en', models.DateTimeField(blank=True, null=True)),
                ('gestionada_en', models.DateTimeField(blank=True, null=True)),
                ('error_codigo', models.CharField(blank=True, max_length=80)),
                ('error_etapa', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credito', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='novedad_operativa_prestador', to='gestion_creditos.credito')),
                ('credito_libranza', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='novedad_operativa_prestador', to='gestion_creditos.creditolibranza')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_operativas_prestadores', to='gestion_creditos.empresa')),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_operativas_prestador_enviadas', to=settings.AUTH_USER_MODEL)),
                ('formalizacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='novedad_operativa', to='contractors.formalizacioncreditoprestador')),
                ('gestionada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_operativas_prestador_gestionadas', to=settings.AUTH_USER_MODEL)),
                ('recibida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_operativas_prestador_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Novedad operativa de prestador',
                'verbose_name_plural': 'Novedades operativas de prestadores',
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_create_contractor_operational_notice', 'Puede crear novedades operativas de prestadores'), ('can_retry_contractor_operational_notice', 'Puede reintentar novedades operativas de prestadores'), ('can_view_contractor_operational_notice', 'Puede ver novedades operativas de prestadores'), ('can_acknowledge_contractor_operational_notice', 'Puede confirmar y gestionar novedades operativas de prestadores')],
                'indexes': [models.Index(fields=['estado', '-created_at'], name='prest_nov_estado_idx'), models.Index(fields=['empresa', '-created_at'], name='prest_nov_empresa_idx')],
            },
        ),
    ]
