# Generated by Django 5.2 on 2026-06-09 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0012_predecisionprestadoraudit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorapplication',
            options={'ordering': ['-created_at'], 'permissions': [('can_review_contractor_application', 'Puede revisar pre-solicitudes contratistas'), ('can_evaluate_contractor_predecision', 'Puede evaluar predecision de prestadores')], 'verbose_name': 'Pre-solicitud contratista', 'verbose_name_plural': 'Pre-solicitudes contratistas'},
        ),
    ]
