# Generated by Django 5.2 on 2026-07-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0013_alter_timelineprestador_tipo_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsimuladorprestador',
            name='plazo_maximo_meses',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddConstraint(
            model_name='configuracionsimuladorprestador',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('activo',), name='unique_simulador_prestador_activo'),
        ),
    ]
