# Generated by Django 5.2 on 2026-06-10 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0013_alter_contractorapplication_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predecisionprestadoraudit',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_contractor_risk_queue', 'Puede ver bandeja de riesgo de prestadores')], 'verbose_name': 'Auditoria de predecision prestador', 'verbose_name_plural': 'Auditorias de predecision prestador'},
        ),
    ]
