# Generated by Django 5.2 on 2026-07-23 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0014_alter_configuracionsimuladorprestador_plazo_maximo_meses_and_more'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionscoreprestador',
            name='accion_error_permanente_centrales',
            field=models.CharField(choices=[('PERMITIR_PARCIAL', 'Permitir evaluacion parcial'), ('REVISION_MANUAL', 'Enviar a revision manual'), ('NO_EVALUABLE', 'Marcar como no evaluable')], default='NO_EVALUABLE', max_length=24),
        ),
        migrations.AddField(
            model_name='configuracionscoreprestador',
            name='accion_error_transitorio_centrales',
            field=models.CharField(choices=[('PERMITIR_PARCIAL', 'Permitir evaluacion parcial'), ('REVISION_MANUAL', 'Enviar a revision manual'), ('NO_EVALUABLE', 'Marcar como no evaluable')], default='REVISION_MANUAL', max_length=24),
        ),
        migrations.AddField(
            model_name='configuracionscoreprestador',
            name='accion_sin_informacion_centrales',
            field=models.CharField(choices=[('PERMITIR_PARCIAL', 'Permitir evaluacion parcial'), ('REVISION_MANUAL', 'Enviar a revision manual'), ('NO_EVALUABLE', 'Marcar como no evaluable')], default='REVISION_MANUAL', max_length=24),
        ),
        migrations.AddField(
            model_name='configuracionscoreprestador',
            name='permite_evaluar_sin_hdc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionscoreprestador',
            name='permite_evaluar_sin_midecisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionscoreprestador',
            name='peso_hdcplus',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Peso HDCPlus/comportamiento para politicas duales.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='configuracionscoreprestador',
            name='peso_midecisor',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Peso MiDecisor para politicas duales. Nulo conserva la politica historica.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='configuracionscoreprestador',
            name='requiere_hdcplus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionscoreprestador',
            name='requiere_midecisor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionscoreprestador',
            name='vigencia_hdcplus_dias',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='configuracionscoreprestador',
            name='vigencia_midecisor_dias',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='estado_hdcplus',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='estado_midecisor',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='evaluacion_centrales_completa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='snapshot_hdcplus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_prestador_hdcplus', to='integrations.consultadatacreditosnapshot'),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='snapshot_midecisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_prestador_midecisor', to='integrations.consultadatacreditosnapshot'),
        ),
    ]
