# Generated by Django 5.2 on 2026-06-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0014_alter_predecisionprestadoraudit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorapplication',
            options={'ordering': ['-created_at'], 'permissions': [('can_review_contractor_application', 'Puede revisar pre-solicitudes contratistas'), ('can_evaluate_contractor_predecision', 'Puede evaluar predecision de prestadores'), ('can_originate_contractor_credit', 'Puede originar credito de prestadores')], 'verbose_name': 'Pre-solicitud contratista', 'verbose_name_plural': 'Pre-solicitudes contratistas'},
        ),
    ]
