# Generated by Django 5.2 on 2026-06-10 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0015_alter_contractorapplication_options'),
        ('gestion_creditos', '0034_add_risk_diagnostic_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadPagadorPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO_PRESTADOR_EN_REVISION', 'Credito prestador en revision')], default='CREDITO_PRESTADOR_EN_REVISION', max_length=60)),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('ENVIADA', 'Enviada'), ('ERROR', 'Error')], default='REGISTRADA', max_length=20)),
                ('destinatarios', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_pagador_prestador_creadas', to=settings.AUTH_USER_MODEL)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_pagador_prestador', to='gestion_creditos.credito')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_pagador_prestador', to='gestion_creditos.empresa')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_pagador', to='contractors.contractorapplication')),
            ],
            options={
                'verbose_name': 'Novedad pagador prestador',
                'verbose_name_plural': 'Novedades pagador prestador',
                'ordering': ['-created_at'],
                'permissions': [('can_notify_contractor_payer', 'Puede notificar novedad de prestador al pagador')],
                'indexes': [models.Index(fields=['empresa', 'created_at'], name='nov_pag_prest_emp_fecha_idx'), models.Index(fields=['estado', 'created_at'], name='nov_pag_prest_estado_idx')],
                'constraints': [models.UniqueConstraint(fields=('credito', 'tipo'), name='unique_novedad_pagador_prestador_credito_tipo')],
            },
        ),
    ]
