# Generated by Django 5.2 on 2026-07-23 03:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0015_configuracionscoreprestador_accion_error_permanente_centrales_and_more'),
        ('gestion_creditos', '0035_secuencianumerocredito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionscoreprestador',
            name='tolerancia_ingreso_contractual',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.15000'), help_text='Diferencia relativa tolerada entre ingreso explícito y derivado.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='confianza_forma_pago',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='evidencia_forma_pago',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='forma_pago',
            field=models.CharField(choices=[('MENSUAL', 'Mensual'), ('QUINCENAL', 'Quincenal'), ('SEMANAL', 'Semanal'), ('POR_ENTREGABLE', 'Por entregable'), ('CONTRA_FACTURA', 'Contra factura'), ('VARIABLE', 'Variable'), ('NO_IDENTIFICADA', 'No identificada'), ('OTRO', 'Otro')], default='NO_IDENTIFICADA', max_length=24),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='frecuencia_pago',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='fuente_forma_pago',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='contractorapplication',
            name='valor_mensual_contractual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='formalizacioncreditoprestador',
            name='identidad_documento_validada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formalizacioncreditoprestador',
            name='identidad_evidencia_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='formalizacioncreditoprestador',
            name='identidad_firmante_coincide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formalizacioncreditoprestador',
            name='identidad_selfie_validada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='capacidad_disponible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='cuota_mensual_hdc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='cuota_nueva_estimada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='ingreso_contractual_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='metodo_ingreso_contractual',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='relacion_carga_ingreso',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='version_calculo_ingreso',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contractorapplication',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('DOCUMENTOS_PENDIENTES', 'Documentos pendientes'), ('DOCUMENTOS_CARGADOS', 'Documentos cargados'), ('EVALUACION_PENDIENTE', 'Evaluación pendiente'), ('EN_EVALUACION', 'En evaluación'), ('EVALUACION_COMPLETADA', 'Evaluación completada'), ('PENDIENTE_APROBACION_PAGADOR', 'Pendiente aprobación de la empresa'), ('APROBADO_POR_PAGADOR', 'Aprobado por la empresa'), ('NO_APROBADO', 'No aprobado'), ('PENDIENTE_FIRMA', 'Pendiente de firma'), ('FIRMADO', 'Firmado'), ('EN_REVISION', 'En revisión manual')], default='DOCUMENTOS_PENDIENTES', max_length=32),
        ),
        migrations.AlterField(
            model_name='timelineprestador',
            name='tipo_evento',
            field=models.CharField(choices=[('SOLICITUD_REGISTRADA', 'Solicitud registrada'), ('EVALUACION_PENDIENTE', 'Evaluación pendiente'), ('EVALUACION_INICIADA', 'Evaluación iniciada'), ('EVALUACION_COMPLETADA', 'Evaluación completada'), ('REVISION_MANUAL_REQUERIDA', 'Revisión manual requerida'), ('DATOS_MODIFICADOS', 'Datos modificados'), ('DATACREDITO_REUTILIZADO', 'DataCrédito reutilizado'), ('DATACREDITO_CONSULTADO', 'DataCrédito consultado'), ('DATACREDITO_ERROR', 'Error DataCrédito'), ('REVISION_CREADA', 'Revision creada'), ('REVISION_ASIGNADA', 'Revision asignada'), ('REVISION_INICIADA', 'Revision iniciada'), ('SUBSANACION_SOLICITADA', 'Subsanacion solicitada'), ('SUBSANACION_ATENDIDA', 'Subsanacion atendida'), ('VALIDACION_EMPRESA_SOLICITADA', 'Validacion de empresa solicitada'), ('EVALUACION_REINTENTADA', 'Evaluacion reintentada'), ('REVISION_RESUELTA', 'Revision resuelta'), ('REVISION_CANCELADA', 'Revision cancelada'), ('APROBACION_INTERNA_CREADA', 'Aprobacion interna creada'), ('APROBACION_INTERNA_INICIADA', 'Aprobacion interna iniciada'), ('APROBADA_PARA_ORIGINAR', 'Aprobada para originar'), ('DEVUELTA_A_REVISION', 'Devuelta a revision'), ('CERRADA_SIN_ORIGINAR', 'Cerrada sin originar'), ('APROBACION_INTERNA_CANCELADA', 'Aprobacion interna cancelada'), ('ORIGINACION_INICIADA', 'Originacion iniciada'), ('ORIGINACION_COMPLETADA', 'Originacion completada'), ('ORIGINACION_REUTILIZADA', 'Originacion reutilizada'), ('ORIGINACION_ERROR_CONTROLADO', 'Error controlado de originacion'), ('FORMALIZACION_INICIADA', 'Formalizacion iniciada'), ('PAGARE_GENERADO', 'Pagare generado'), ('IDENTIDAD_VALIDADA_FIRMA', 'Identidad validada para firma'), ('ENVIO_FIRMA_INICIADO', 'Envio a firma iniciado'), ('PENDIENTE_FIRMA', 'Pendiente de firma'), ('FIRMA_CONFIRMADA', 'Firma confirmada'), ('FIRMA_ERROR_CONTROLADO', 'Error controlado de firma'), ('FORMALIZACION_REUTILIZADA', 'Formalizacion reutilizada'), ('NOVEDAD_OPERATIVA_GENERADA', 'Novedad operativa generada'), ('NOVEDAD_OPERATIVA_ENVIO_INICIADO', 'Envio de novedad operativa iniciado'), ('NOVEDAD_OPERATIVA_ENVIADA', 'Novedad operativa enviada'), ('NOVEDAD_OPERATIVA_RECIBIDA', 'Novedad operativa recibida'), ('NOVEDAD_OPERATIVA_GESTIONADA', 'Novedad operativa gestionada'), ('NOVEDAD_OPERATIVA_ERROR', 'Error de novedad operativa'), ('NOVEDAD_OPERATIVA_REENVIO', 'Reenvio de novedad operativa'), ('APROBACION_PAGADOR_PENDIENTE', 'Aprobacion de empresa pendiente'), ('APROBACION_PAGADOR_REGISTRADA', 'Decision de empresa registrada')], max_length=40),
        ),
        migrations.CreateModel(
            name='AprobacionPagadorPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REQUIERE_AJUSTE', 'Requiere ajuste'), ('INVALIDADA', 'Invalidada')], default='PENDIENTE', max_length=24)),
                ('motivo', models.CharField(blank=True, choices=[('CONFIRMACION_COMPLETA', 'Confirmación completa'), ('CONTRATO_NO_VIGENTE', 'Contrato no vigente'), ('VINCULO_NO_CONFIRMADO', 'Vínculo no confirmado'), ('FORMA_PAGO_NO_MENSUAL', 'Forma de pago no mensual'), ('VALORES_INCONSISTENTES', 'Valores inconsistentes'), ('SIN_CAPACIDAD_OPERATIVA', 'Sin capacidad operativa de pago'), ('DATOS_MODIFICADOS', 'Datos modificados'), ('OTRO', 'Otro')], max_length=40)),
                ('observacion', models.TextField(blank=True)),
                ('version_datos', models.CharField(max_length=64)),
                ('version_solicitud', models.PositiveIntegerField(default=1)),
                ('confirma_vinculo', models.BooleanField(default=False)),
                ('confirma_contrato_vigente', models.BooleanField(default=False)),
                ('confirma_forma_pago_mensual', models.BooleanField(default=False)),
                ('confirma_valores_contractuales', models.BooleanField(default=False)),
                ('confirma_capacidad_operativa', models.BooleanField(default=False)),
                ('acepta_gestionar_pago', models.BooleanField(default=False)),
                ('snapshot_condiciones', models.JSONField(blank=True, default=dict)),
                ('decidida_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobacion_interna', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aprobacion_pagador', to='contractors.aprobacioninternaprestador')),
                ('decidida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_pagador_prestadores', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones_prestadores', to='gestion_creditos.empresa')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones_pagador', to='contractors.contractorapplication')),
            ],
            options={
                'verbose_name': 'Aprobación de pagador para prestador',
                'verbose_name_plural': 'Aprobaciones de pagador para prestadores',
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_decide_contractor_payer_approval', 'Puede decidir aprobaciones de prestadores como pagador')],
                'indexes': [models.Index(fields=['empresa', 'estado'], name='prest_pagador_emp_estado_idx'), models.Index(fields=['solicitud', '-created_at'], name='prest_pagador_solic_idx')],
            },
        ),
    ]
