# Generated by Django 5.2 on 2026-06-12 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0016_novedadpagadorprestador'),
        ('gestion_creditos', '0034_add_risk_diagnostic_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelinePrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('SOLICITUD_CREADA', 'Solicitud creada'), ('DOCUMENTOS_CARGADOS', 'Documentos cargados'), ('ANALISIS_IA_CONTRATO', 'Analisis IA contrato'), ('PREDECISION_EJECUTADA', 'Predecision ejecutada'), ('AUDITORIA_PREDECISION_CREADA', 'Auditoria predecision creada'), ('ORIGINADO_EN_REVISION', 'Originado en revision'), ('NOVEDAD_PAGADOR_REGISTRADA', 'Novedad pagador registrada'), ('FIRMA_V2_PREPARADA', 'Firma V2 preparada'), ('DRAFT_FIRMA_V2_CREADO', 'Draft firma V2 creado')], max_length=60)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('estado_resultante', models.CharField(blank=True, max_length=60)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_prestador', to='gestion_creditos.credito')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_operativo', to='contractors.contractorapplication')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_prestadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timeline operativo prestador',
                'verbose_name_plural': 'Timeline operativo prestadores',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['solicitud', '-created_at'], name='tl_prest_solicitud_fecha_idx'), models.Index(fields=['credito', '-created_at'], name='tl_prest_credito_fecha_idx'), models.Index(fields=['tipo_evento', '-created_at'], name='tl_prest_evento_fecha_idx')],
            },
        ),
    ]
