# Generated by Django 5.2 on 2026-07-24 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0016_configuracionscoreprestador_tolerancia_ingreso_contractual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionscoreprestador',
            options={'ordering': ['-fecha_vigencia_desde', '-id'], 'permissions': [('can_activate_contractor_score_policy', 'Puede activar politicas de score de prestadores')], 'verbose_name': 'Configuracion de score de prestadores', 'verbose_name_plural': 'Configuraciones de score de prestadores'},
        ),
        migrations.CreateModel(
            name='CambioPoliticaScorePrestadorAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('ACTIVACION', 'Activacion'), ('REACTIVACION', 'Reactivacion'), ('SIN_CAMBIO', 'Sin cambio')], max_length=16)),
                ('snapshot_anterior', models.JSONField(blank=True, default=dict)),
                ('snapshot_nuevo', models.JSONField(default=dict)),
                ('clave_idempotencia', models.CharField(max_length=64, unique=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_politica_score_prestador', to=settings.AUTH_USER_MODEL)),
                ('politica_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_como_politica_anterior', to='contractors.configuracionscoreprestador')),
                ('politica_nueva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_como_politica_nueva', to='contractors.configuracionscoreprestador')),
            ],
            options={
                'verbose_name': 'Auditoria de cambio de politica de score de prestadores',
                'verbose_name_plural': 'Auditorias de cambios de politica de score de prestadores',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
