# Generated by Django 5.2 on 2026-08-25 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0017_alter_configuracionscoreprestador_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formalizacioncreditoprestador',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('can_prepare_contractor_formalization', 'Puede preparar formalizaciones de prestadores'), ('can_retry_contractor_signature', 'Puede reintentar firmas de prestadores'), ('can_view_contractor_formalization', 'Puede ver formalizaciones de prestadores'), ('can_prepare_contractor_transfer', 'Puede preparar transferencia de creditos de prestadores'), ('can_confirm_contractor_disbursement', 'Puede confirmar desembolso de creditos de prestadores')], 'verbose_name': 'Formalizacion de credito de prestador', 'verbose_name_plural': 'Formalizaciones de creditos de prestadores'},
        ),
    ]
