# Generated by Django 5.2 on 2026-09-12 19:33

import contractors.models
import gestion_creditos.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0018_alter_formalizacioncreditoprestador_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorapplicationdocument',
            name='archivo',
            field=models.FileField(storage=gestion_creditos.storage.DocumentosSolicitudStorage(), upload_to=contractors.models.ruta_documento_prestador),
        ),
    ]
