# Generated by Django 5.2 on 2026-06-12 23:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0018_allow_application_amount_term_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionportalcontratistas',
            name='factor_seguro_vida',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.003711'), max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AddField(
            model_name='configuracionportalcontratistas',
            name='fondo_garantia_incluye_iva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionportalcontratistas',
            name='iva_fondo_garantia',
            field=models.DecimalField(decimal_places=4, default=Decimal('19.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AddField(
            model_name='configuracionportalcontratistas',
            name='seguro_vida_financiado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionportalcontratistas',
            name='tasa_fondo_garantia',
            field=models.DecimalField(decimal_places=4, default=Decimal('2.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.CreateModel(
            name='SimulacionPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('plazo_meses', models.PositiveSmallIntegerField()),
                ('tasa_mensual', models.DecimalField(decimal_places=4, max_digits=7)),
                ('tea', models.DecimalField(decimal_places=4, max_digits=9)),
                ('costo_originacion', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva_costo_originacion', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fondo_garantia_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fondo_garantia_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fondo_garantia_iva', models.DecimalField(decimal_places=2, max_digits=14)),
                ('seguro_vida', models.DecimalField(decimal_places=2, max_digits=14)),
                ('capital_total_financiado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=14)),
                ('intereses_estimados', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_estimado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('version_politica', models.CharField(max_length=40)),
                ('aceptada', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aceptada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simulaciones_prestador_aceptadas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulaciones_prestador', to='contractors.contractorapplication')),
            ],
            options={
                'verbose_name': 'Simulacion prestador',
                'verbose_name_plural': 'Simulaciones prestador',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['solicitud', 'aceptada'], name='sim_prest_solic_acept_idx'), models.Index(fields=['created_at'], name='sim_prest_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('aceptada', True)), fields=('solicitud',), name='unique_simulacion_prestador_aceptada')],
            },
        ),
    ]
