# Generated by Django 5.2 on 2026-06-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0019_configuracionportalcontratistas_factor_seguro_vida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineprestador',
            name='tipo_evento',
            field=models.CharField(choices=[('SOLICITUD_CREADA', 'Solicitud creada'), ('DOCUMENTOS_CARGADOS', 'Documentos cargados'), ('ANALISIS_IA_CONTRATO', 'Analisis IA contrato'), ('PREDECISION_EJECUTADA', 'Predecision ejecutada'), ('AUDITORIA_PREDECISION_CREADA', 'Auditoria predecision creada'), ('ORIGINADO_EN_REVISION', 'Originado en revision'), ('NOVEDAD_PAGADOR_REGISTRADA', 'Novedad pagador registrada'), ('FIRMA_V2_PREPARADA', 'Firma V2 preparada'), ('DRAFT_FIRMA_V2_CREADO', 'Draft firma V2 creado'), ('SIMULACION_ACEPTADA', 'Simulacion aceptada')], max_length=60),
        ),
    ]
