# Generated by Django 5.2 on 2026-10-08 02:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0019_captura_documental_privada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoNetoVerificadoPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('accion', models.CharField(choices=[('VERIFICADO', 'Verificado'), ('INVALIDADO', 'Invalidado')], max_length=12)),
                ('fuente', models.CharField(default='MANUAL_VERIFICADA', editable=False, max_length=24)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_corte', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('verificado_en', models.DateTimeField(auto_now_add=True)),
                ('evidencias', models.JSONField(blank=True, default=list)),
                ('observacion', models.CharField(max_length=1000)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_netos_verificados', to='contractors.contractorapplication')),
                ('verificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_prestador_verificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'permissions': [('can_verify_contractor_net_income', 'Puede verificar e invalidar ingreso neto de prestadores')],
                'constraints': [models.UniqueConstraint(fields=('solicitud', 'version'), name='unique_prestador_ingreso_version'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='prestador_ingreso_version_positiva'), models.CheckConstraint(condition=models.Q(models.Q(('accion', 'VERIFICADO'), ('fecha_corte__isnull', False), ('monto__gt', 0), ('monto__isnull', False), ('vigente_hasta__isnull', False)), models.Q(('accion', 'INVALIDADO'), ('fecha_corte__isnull', True), ('monto__isnull', True), ('vigente_hasta__isnull', True)), _connector='OR'), name='prestador_ingreso_datos_accion')],
            },
        ),
    ]
