# Generated by Django 5.2 on 2026-06-14 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0020_alter_timelineprestador_tipo_evento'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predecisionprestadoraudit',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_contractor_risk_queue', 'Puede ver bandeja de riesgo de prestadores'), ('can_run_contractor_datacredito_evaluation', 'Puede evaluar DataCredito de prestadores'), ('can_force_contractor_datacredito_refresh', 'Puede forzar consulta DataCredito de prestadores')], 'verbose_name': 'Auditoria de predecision prestador', 'verbose_name_plural': 'Auditorias de predecision prestador'},
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='datacredito_modo',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='decisor_consultado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='decisor_reutilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='historial_consultado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='historial_reutilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='justificacion_consulta_forzada',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='snapshot_decisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_prestador_decisor', to='integrations.consultadatacreditosnapshot'),
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='snapshot_historial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_prestador_historial', to='integrations.consultadatacreditosnapshot'),
        ),
    ]
