# Generated by Django 5.2 on 2026-06-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0021_alter_predecisionprestadoraudit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineprestador',
            name='tipo_evento',
            field=models.CharField(choices=[('SOLICITUD_CREADA', 'Solicitud creada'), ('DOCUMENTOS_CARGADOS', 'Documentos cargados'), ('ANALISIS_IA_CONTRATO', 'Analisis IA contrato'), ('PREDECISION_EJECUTADA', 'Predecision ejecutada'), ('AUDITORIA_PREDECISION_CREADA', 'Auditoria predecision creada'), ('ORIGINADO_EN_REVISION', 'Originado en revision'), ('NOVEDAD_PAGADOR_REGISTRADA', 'Novedad pagador registrada'), ('FIRMA_V2_PREPARADA', 'Firma V2 preparada'), ('DRAFT_FIRMA_V2_CREADO', 'Draft firma V2 creado'), ('SIMULACION_ACEPTADA', 'Simulacion aceptada'), ('DATACREDITO_EVALUACION_INICIADA', 'DataCredito evaluacion iniciada'), ('DATACREDITO_SNAPSHOT_REUTILIZADO', 'DataCredito snapshot reutilizado'), ('DATACREDITO_CONSULTA_REALIZADA', 'DataCredito consulta realizada'), ('DATACREDITO_EVALUACION_COMPLETADA', 'DataCredito evaluacion completada'), ('DATACREDITO_EVALUACION_FALLIDA', 'DataCredito evaluacion fallida'), ('DATACREDITO_CONSULTA_FORZADA', 'DataCredito consulta forzada')], max_length=60),
        ),
    ]
