# Generated by Django 5.2 on 2026-06-14 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0022_alter_timelineprestador_tipo_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predecisionprestadoraudit',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_contractor_risk_queue', 'Puede ver bandeja de riesgo de prestadores'), ('can_run_contractor_datacredito_evaluation', 'Puede evaluar DataCredito de prestadores'), ('can_force_contractor_datacredito_refresh', 'Puede forzar consulta DataCredito de prestadores'), ('can_register_uat_datacredito_authorization', 'Puede registrar autorizacion DataCredito UAT de prestadores')], 'verbose_name': 'Auditoria de predecision prestador', 'verbose_name_plural': 'Auditorias de predecision prestador'},
        ),
        migrations.AlterField(
            model_name='timelineprestador',
            name='tipo_evento',
            field=models.CharField(choices=[('SOLICITUD_CREADA', 'Solicitud creada'), ('DOCUMENTOS_CARGADOS', 'Documentos cargados'), ('ANALISIS_IA_CONTRATO', 'Analisis IA contrato'), ('PREDECISION_EJECUTADA', 'Predecision ejecutada'), ('AUDITORIA_PREDECISION_CREADA', 'Auditoria predecision creada'), ('ORIGINADO_EN_REVISION', 'Originado en revision'), ('NOVEDAD_PAGADOR_REGISTRADA', 'Novedad pagador registrada'), ('FIRMA_V2_PREPARADA', 'Firma V2 preparada'), ('DRAFT_FIRMA_V2_CREADO', 'Draft firma V2 creado'), ('SIMULACION_ACEPTADA', 'Simulacion aceptada'), ('DATACREDITO_EVALUACION_INICIADA', 'DataCredito evaluacion iniciada'), ('DATACREDITO_SNAPSHOT_REUTILIZADO', 'DataCredito snapshot reutilizado'), ('DATACREDITO_CONSULTA_REALIZADA', 'DataCredito consulta realizada'), ('DATACREDITO_EVALUACION_COMPLETADA', 'DataCredito evaluacion completada'), ('DATACREDITO_EVALUACION_FALLIDA', 'DataCredito evaluacion fallida'), ('DATACREDITO_CONSULTA_FORZADA', 'DataCredito consulta forzada'), ('DATACREDITO_AUTORIZACION_ACEPTADA', 'DataCredito autorizacion aceptada'), ('DATACREDITO_AUTORIZACION_REVOCADA', 'DataCredito autorizacion revocada'), ('DATACREDITO_AUTORIZACION_UAT_REGISTRADA', 'DataCredito autorizacion UAT registrada'), ('DATACREDITO_CONSULTA_BLOQUEADA_SIN_AUTORIZACION', 'DataCredito consulta bloqueada sin autorizacion')], max_length=60),
        ),
        migrations.CreateModel(
            name='AutorizacionConsultaDatacreditoPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizado', models.BooleanField(default=True)),
                ('version_texto', models.CharField(max_length=80)),
                ('texto_hash', models.CharField(max_length=128)),
                ('finalidad', models.CharField(max_length=240)),
                ('accepted_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('FORMULARIO_PUBLICO', 'Formulario publico'), ('STAFF_UAT', 'Staff UAT'), ('MIGRACION_CONTROLADA', 'Migracion controlada')], max_length=40)),
                ('justificacion', models.CharField(blank=True, max_length=500)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_datacredito', to='contractors.contractorapplication')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_datacredito_prestador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autorizacion consulta DataCredito prestador',
                'verbose_name_plural': 'Autorizaciones consulta DataCredito prestador',
                'ordering': ['-accepted_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='predecisionprestadoraudit',
            name='autorizacion_datacredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_predecision', to='contractors.autorizacionconsultadatacreditoprestador'),
        ),
        migrations.AddIndex(
            model_name='autorizacionconsultadatacreditoprestador',
            index=models.Index(fields=['solicitud', 'version_texto', 'revoked_at'], name='auth_dc_solic_version_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizacionconsultadatacreditoprestador',
            index=models.Index(fields=['usuario', 'accepted_at'], name='auth_dc_usuario_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizacionconsultadatacreditoprestador',
            index=models.Index(fields=['source', 'accepted_at'], name='auth_dc_source_fecha_idx'),
        ),
    ]
